import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ApiProblem } from '@/lib/api/problem';
import { isUuid } from '@/lib/cart/contracts';
import { formatEuro } from '@/lib/checkout/contracts';
import { formatOrderDate, orderStateLabel } from '@/lib/orders/contracts';
import { subOrderStateLabel } from '@/lib/suborders/contracts';
import { getAdminOrder } from '@/lib/admin/server';
interface Props{params:Promise<{id:string}>}
function Address({title,value}:{title:string;value:{nombre_destinatario:string;direccion:string;codigo_postal:string;ciudad:string;pais:string;empresa?:string;direccion_adicional?:string;provincia?:string}}){return <article className="address-snapshot"><h2>{title}</h2><address><strong>{value.nombre_destinatario}</strong>{value.empresa&&<span>{value.empresa}</span>}<span>{value.direccion}</span>{value.direccion_adicional&&<span>{value.direccion_adicional}</span>}<span>{value.codigo_postal} {value.ciudad}{value.provincia?`, ${value.provincia}`:''}</span><span>{value.pais}</span></address></article>}
export default async function AdminOrderPage({params}:Props){const {id}=await params;if(!isUuid(id))notFound();let order;try{order=await getAdminOrder(id)}catch(error){if(error instanceof ApiProblem&&[403,404].includes(error.problem.status))notFound();return <section className="screen-state screen-state-error"><h1>No hemos podido cargar el pedido</h1>{error instanceof ApiProblem&&<p className="request-reference">Referencia: {error.problem.request_id}</p>}<Link className="button secondary" href={`/admin/pedidos/${encodeURIComponent(id)}`}>Reintentar</Link></section>}return <section className="private-page order-detail-page"><nav className="breadcrumbs"><Link href="/admin">Dashboard</Link><span>/</span><Link href="/admin/pedidos">Pedidos</Link><span>/</span><span>{order.numero_pedido}</span></nav><header className="private-heading order-detail-heading"><div><p className="eyebrow">PT-ADM-007</p><h1>Pedido {order.numero_pedido}</h1><p>Realizado el {formatOrderDate(order.created_at)}</p></div><span className={`status-badge status-${order.estado}`}>{orderStateLabel(order.estado)}</span></header><div className="order-detail-layout"><div><section className="order-lines"><h2>Líneas congeladas</h2>{order.lineas.map(line=><article className="order-line" key={line.id}><div><h3>{line.nombre_vino}</h3><p>{line.bodega}{line.anada===undefined?'':` · Añada ${line.anada}`}</p><small>{line.cantidad} × {formatEuro(line.precio_unitario)}</small></div><strong>{formatEuro(line.importe_total)}</strong></article>)}</section><section className="admin-suborders"><h2>SubPedidos operativos</h2>{order.subpedidos.length===0?<p>No hay SubPedidos asociados.</p>:order.subpedidos.map(item=><article key={item.id}><div><strong>{item.id.slice(0,8)}</strong><span className={`status-badge status-${item.estado}`}>{subOrderStateLabel(item.estado)}</span></div><dl><div><dt>Total</dt><dd>{formatEuro(item.total)}</dd></div><div><dt>Transportista</dt><dd>{item.tracking.transportista??'Pendiente'}</dd></div><div><dt>Seguimiento</dt><dd>{item.tracking.numero_seguimiento??'Pendiente'}</dd></div></dl></article>)}</section><div className="snapshot-grid"><Address title="Dirección de envío" value={order.direccion_envio_snapshot}/><Address title="Dirección de facturación" value={order.direccion_facturacion_snapshot}/></div></div><aside className="checkout-summary order-totals"><h2>Resumen</h2><dl><div><dt>Subtotal</dt><dd>{formatEuro(order.totales.subtotal)}</dd></div><div><dt>Envío</dt><dd>{formatEuro(order.totales.gastos_envio)}</dd></div><div><dt>Impuestos</dt><dd>{formatEuro(order.totales.impuestos)}</dd></div><div><dt>Descuentos</dt><dd>−{formatEuro(order.totales.descuentos)}</dd></div><div className="summary-total"><dt>Total</dt><dd>{formatEuro(order.totales.total)}</dd></div></dl>{order.comprador_id&&<p>Comprador: <code>{order.comprador_id}</code></p>}</aside></div></section>}
