import { Injectable } from '@nestjs/common';
import type { PoolClient } from 'pg';
import { DatabaseService } from '../../common/database/database.service.js';
import type { StripeWebhookEvent, WebhookAck } from './dto/stripe-webhook.dto.js';

export type WebhookResult={kind:'ok';ack:WebhookAck}|{kind:'missing'}|{kind:'conflict';message:string};
interface PaymentRow { id:string;pedido_id:string;estado:WebhookAck['pago_estado'];stripe_checkout_session_id:string|null;total_cobrado:string }
interface OrderRow { id:string;numero_pedido:string;comprador_id:string;carrito_id:string;estado:WebhookAck['pedido_estado'];subtotal:string;gastos_envio:string;impuestos:string;descuentos:string;total:string;direccion_facturacion_snapshot:Record<string,unknown> }
interface CartLine { id:string;vino_id:string;cantidad:number;precio_unitario:string;importe_total:string;bodega_id:string;nombre_vino:string;anada:number|null;stock_disponible:number;bodega_nombre:string;bodega_razon_social:string|null;bodega_cif_vat:string|null;bodega_direccion:string|null;bodega_codigo_postal:string|null;bodega_ciudad:string|null;bodega_pais:string|null;comision:string|null;cuenta_stripe_connect_id:string|null;stripe_account_id:string|null }
interface Group { bodegaId:string;bodegaName:string;commissionRate:string;connectAccountId:string;connectRecordId:string;subtotalCents:number;discountCents:number;netMerchandiseCents:number;lines:CartLine[];shippingCents:number;taxCents:number;totalCents:number;commissionCents:number;payoutCents:number }
class MaterializationConflictError extends Error {}

@Injectable()
export class StripeWebhookRepository {
  constructor(private readonly database:DatabaseService){}
  async procesar(event:StripeWebhookEvent,pedidoId:string,pagoId:string):Promise<WebhookResult>{try{return await this.database.withTransaction(async client=>{
    const payments=await client.query<PaymentRow>(`SELECT id,pedido_id,estado,stripe_checkout_session_id,total_cobrado::text FROM pago WHERE id=$1 FOR UPDATE`,[pagoId]);const payment=payments.rows[0];if(payment===undefined)return{kind:'missing'};
    const orders=await client.query<OrderRow>(`SELECT id,numero_pedido,comprador_id,carrito_id,estado,subtotal::text,gastos_envio::text,impuestos::text,descuentos::text,total::text,direccion_facturacion_snapshot FROM pedido WHERE id=$1 FOR UPDATE`,[pedidoId]);const order=orders.rows[0];if(order===undefined)return{kind:'missing'};if(payment.pedido_id!==pedidoId)return{kind:'conflict',message:'La relación Pedido–Pago no coincide con la metadata.'};
    if(this.cents(payment.total_cobrado)!==event.data.object.amount_total||event.data.object.currency!=='eur')return{kind:'conflict',message:'El importe o moneda no coincide con el Pago.'};
    const ledger=await client.query<{stripe_event_id:string}>(`INSERT INTO evento_webhook_stripe(stripe_event_id,tipo_evento,pago_id,procesado_at,resultado) VALUES($1,$2,$3,now(),'correcto') ON CONFLICT(stripe_event_id) DO NOTHING RETURNING stripe_event_id`,[event.id,event.type,pagoId]);
    if(ledger.rows[0]===undefined)return{kind:'ok',ack:this.ack(event.id,'duplicate',pedidoId,payment.estado,order.estado)};
    const success=event.type==='checkout.session.async_payment_succeeded'||(event.type==='checkout.session.completed'&&event.data.object.payment_status==='paid');
    if(success)return this.confirm(client,event,order,payment);
    if(event.type==='checkout.session.completed')return{kind:'ok',ack:this.ack(event.id,'ignored',pedidoId,payment.estado,order.estado)};
    if(event.data.object.id!==payment.stripe_checkout_session_id||payment.estado==='pagado')return{kind:'ok',ack:this.ack(event.id,'ignored',pedidoId,payment.estado,order.estado)};
    const state=event.type==='checkout.session.async_payment_failed'?'fallido':'cancelado';await client.query(`UPDATE pago SET estado=$2,updated_at=now() WHERE id=$1`,[payment.id,state]);await client.query(`INSERT INTO auditoria(tipo_entidad,entidad_id,accion,valor_anterior,valor_nuevo,descripcion,sistema) VALUES('pago',$1,'webhook_stripe',jsonb_build_object('estado',$2::text),jsonb_build_object('estado',$3::text),'Evento negativo Stripe validado','stripe')`,[payment.id,payment.estado,state]);return{kind:'ok',ack:this.ack(event.id,'processed',pedidoId,state,order.estado)};
  });}catch(error){if(error instanceof MaterializationConflictError)return{kind:'conflict',message:error.message};throw error;}}
  private async confirm(client:PoolClient,event:StripeWebhookEvent,order:OrderRow,payment:PaymentRow):Promise<WebhookResult>{const existing=await client.query<{total:number}>('SELECT count(*)::int total FROM pedido_item WHERE pedido_id=$1',[order.id]);if(payment.estado==='pagado'&&order.estado==='pagado'&&existing.rows[0]?.total!==0)return{kind:'ok',ack:this.ack(event.id,'processed',order.id,'pagado','pagado')};if(order.estado!=='pendiente_pago'||existing.rows[0]?.total!==0)throw new MaterializationConflictError('El Pedido no admite confirmación o está materializado de forma incoherente.');
    const lines=await client.query<CartLine>(`SELECT ci.id,ci.vino_id,ci.cantidad,ci.precio_unitario::text,ci.importe_total::text,v.bodega_id,v.nombre_comercial nombre_vino,v.anada,v.stock_disponible,b.nombre_comercial bodega_nombre,b.razon_social bodega_razon_social,b.cif_vat bodega_cif_vat,b.direccion_fisica bodega_direccion,b.codigo_postal bodega_codigo_postal,b.ciudad bodega_ciudad,coalesce(b.pais_contacto,b.pais) bodega_pais,b.comision::text,c.id cuenta_stripe_connect_id,c.stripe_account_id FROM carrito_item ci JOIN vino v ON v.id=ci.vino_id JOIN bodega b ON b.id=v.bodega_id LEFT JOIN cuenta_stripe_connect c ON c.bodega_id=b.id AND c.estado_cuenta='activa' AND c.cuenta_verificada AND c.cargos_habilitados AND c.cobros_habilitados WHERE ci.carrito_id=$1 ORDER BY v.id FOR UPDATE OF v`,[order.carrito_id]);if(lines.rows.length===0)throw new MaterializationConflictError('El carrito confirmado no contiene líneas.');for(const line of lines.rows){if(line.stock_disponible<line.cantidad)throw new MaterializationConflictError('Stock insuficiente para materializar el Pedido pagado.');if(line.comision===null)throw new MaterializationConflictError('La bodega no tiene comisión económica configurada.');if(line.cuenta_stripe_connect_id===null||line.stripe_account_id===null)throw new MaterializationConflictError('La bodega no tiene Stripe Connect operativo.');}
    const groups=this.groups(lines.rows,order);let commission=0;for(const group of groups){const sub=await client.query<{id:string}>(`INSERT INTO subpedido(pedido_id,bodega_id,pago_id,subtotal,descuentos,gastos_envio,impuestos,comision_marketplace,total,estado) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'pendiente') RETURNING id`,[order.id,group.bodegaId,payment.id,this.money(group.subtotalCents),this.money(group.discountCents),this.money(group.shippingCents),this.money(group.taxCents),this.money(group.commissionCents),this.money(group.totalCents)]);const subId=sub.rows[0]?.id;if(subId===undefined)throw new Error('No se pudo crear el SubPedido.');for(const line of group.lines){const stock=await client.query<{id:string}>(`UPDATE vino SET stock_disponible=stock_disponible-$2,updated_at=now() WHERE id=$1 AND stock_disponible >= $2 RETURNING id`,[line.vino_id,line.cantidad]);if(stock.rows[0]===undefined)throw new MaterializationConflictError('Stock insuficiente para materializar el Pedido pagado.');await client.query(`INSERT INTO pedido_item(pedido_id,subpedido_id,vino_id,bodega_id,nombre_vino_snapshot,anada_snapshot,bodega_snapshot,precio_unitario,cantidad,importe_total,estado) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'normal')`,[order.id,subId,line.vino_id,group.bodegaId,line.nombre_vino,line.anada,group.bodegaName,line.precio_unitario,line.cantidad,line.importe_total]);}
      await client.query(`INSERT INTO transferencia_stripe(pago_id,subpedido_id,bodega_id,cuenta_stripe_connect_id,importe,moneda,estado) VALUES($1,$2,$3,$4,$5,'EUR','pendiente')`,[payment.id,subId,group.bodegaId,group.connectRecordId,this.money(group.payoutCents)]);
      await this.documentsForGroup(client,order,payment.id,subId,group);
      commission+=group.commissionCents;
    }
    await this.buyerReceipt(client,order,payment.id);
    await client.query(`UPDATE pago SET estado='pagado',referencia_stripe=$2,metodo_pago='stripe',comision_marketplace=$3,fecha_autorizacion=coalesce(fecha_autorizacion,now()),fecha_captura=coalesce(fecha_captura,now()),updated_at=now() WHERE id=$1`,[payment.id,event.data.object.id,this.money(commission)]);await client.query(`UPDATE pedido SET estado='pagado',updated_at=now() WHERE id=$1`,[order.id]);await client.query(`UPDATE carrito SET estado='convertido',fecha_conversion=coalesce(fecha_conversion,now()),updated_at=now() WHERE id=$1`,[order.carrito_id]);await client.query(`INSERT INTO auditoria(tipo_entidad,entidad_id,accion,valor_anterior,valor_nuevo,descripcion,sistema) VALUES('pedido',$1,'pago_confirmado',jsonb_build_object('estado',$2::text),jsonb_build_object('estado','pagado','stripe_event_id',$3::text),'Pago confirmado y pedido materializado; reparto pendiente de transferencia','stripe')`,[order.id,order.estado,event.id]);return{kind:'ok',ack:this.ack(event.id,'processed',order.id,'pagado','pagado')};}
  private groups(lines:CartLine[],order:OrderRow):Group[]{const map=new Map<string,Group>();for(const line of lines){const found=map.get(line.bodega_id);if(found===undefined)map.set(line.bodega_id,{bodegaId:line.bodega_id,bodegaName:line.bodega_nombre,commissionRate:line.comision??'0',connectAccountId:line.stripe_account_id??'',connectRecordId:line.cuenta_stripe_connect_id??'',subtotalCents:this.cents(line.importe_total),discountCents:0,netMerchandiseCents:0,lines:[line],shippingCents:0,taxCents:0,totalCents:0,commissionCents:0,payoutCents:0});else{found.lines.push(line);found.subtotalCents+=this.cents(line.importe_total);}}const groups=[...map.values()].sort((a,b)=>a.bodegaId.localeCompare(b.bodegaId));this.allocate(groups,this.cents(order.descuentos),'discountCents');this.allocate(groups,this.cents(order.gastos_envio),'shippingCents');this.allocate(groups,this.cents(order.impuestos),'taxCents');for(const group of groups){group.netMerchandiseCents=group.subtotalCents-group.discountCents;if(group.netMerchandiseCents<0)throw new MaterializationConflictError('Los descuentos superan el importe del vino.');group.commissionCents=Math.round(group.netMerchandiseCents*Number(group.commissionRate)/100);group.totalCents=group.netMerchandiseCents+group.shippingCents+group.taxCents;group.payoutCents=group.totalCents-group.commissionCents;}const expected=this.cents(order.total),actual=groups.reduce((sum,group)=>sum+group.totalCents,0);if(expected!==actual)throw new MaterializationConflictError('El reparto no coincide con el total cobrado.');return groups;}
  private allocate(groups:Group[],amount:number,key:'discountCents'|'shippingCents'|'taxCents'):void{const base=groups.reduce((sum,group)=>sum+group.subtotalCents,0);let assigned=0;groups.forEach((group,index)=>{const value=index===groups.length-1?amount-assigned:Math.floor(amount*group.subtotalCents/base);group[key]=value;assigned+=value;});}
  private async buyerReceipt(client:PoolClient,order:OrderRow,paymentId:string):Promise<void>{const number=await this.nextNumber(client,'justificante_cliente','REC');await client.query(`INSERT INTO documento_economico(tipo,numero_documento,pedido_id,pago_id,emisor_snapshot,receptor_snapshot,importes_snapshot,moneda,leyenda) VALUES('justificante_cliente',$1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,'EUR',$7) ON CONFLICT(pedido_id,tipo) WHERE tipo='justificante_cliente' DO NOTHING`,[number,order.id,paymentId,JSON.stringify({nombre:'Teralya',rol:'intermediario_tecnologico_y_de_pago'}),JSON.stringify(order.direccion_facturacion_snapshot),JSON.stringify({subtotal:order.subtotal,descuentos:order.descuentos,transporte:order.gastos_envio,impuestos:order.impuestos,total_pagado:order.total,numero_pedido:order.numero_pedido}),'Justificante de la transacción del dinero. No es una factura de compra del vino; la factura, si se solicita, corresponde a la bodega vendedora.']);}
  private async documentsForGroup(client:PoolClient,order:OrderRow,paymentId:string,suborderId:string,group:Group):Promise<void>{const line=group.lines[0];if(line===undefined)throw new Error('Grupo económico sin bodega.');const winery={nombre_comercial:group.bodegaName,razon_social:line.bodega_razon_social,cif_vat:line.bodega_cif_vat,direccion:line.bodega_direccion,codigo_postal:line.bodega_codigo_postal,ciudad:line.bodega_ciudad,pais:line.bodega_pais};const amounts={subtotal_vino:this.money(group.subtotalCents),descuentos:this.money(group.discountCents),vino_neto:this.money(group.netMerchandiseCents),transporte:this.money(group.shippingCents),impuestos:this.money(group.taxCents),comision_teralya:this.money(group.commissionCents),importe_bodega:this.money(group.payoutCents),total_cliente:this.money(group.totalCents),porcentaje_comision:group.commissionRate};
    const settlement=await this.nextNumber(client,'liquidacion_bodega','LIQ');await client.query(`INSERT INTO documento_economico(tipo,numero_documento,pedido_id,pago_id,subpedido_id,bodega_id,emisor_snapshot,receptor_snapshot,importes_snapshot,moneda,leyenda) VALUES('liquidacion_bodega',$1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb,'EUR',$9) ON CONFLICT(subpedido_id,tipo) WHERE subpedido_id IS NOT NULL DO NOTHING`,[settlement,order.id,paymentId,suborderId,group.bodegaId,JSON.stringify({nombre:'Teralya',rol:'intermediario_tecnologico_y_de_pago'}),JSON.stringify(winery),JSON.stringify(amounts),'Liquidación económica del subpedido: importe de vino neto de descuentos menos comisión, más el transporte y los impuestos atribuibles.']);
    const invoice=await this.nextNumber(client,'factura_comision','FAC');await client.query(`INSERT INTO documento_economico(tipo,numero_documento,pedido_id,pago_id,subpedido_id,bodega_id,emisor_snapshot,receptor_snapshot,importes_snapshot,moneda,leyenda) VALUES('factura_comision',$1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb,'EUR',$9) ON CONFLICT(subpedido_id,tipo) WHERE subpedido_id IS NOT NULL DO NOTHING`,[invoice,order.id,paymentId,suborderId,group.bodegaId,JSON.stringify({nombre:'Teralya',rol:'prestador_del_servicio_de_intermediacion'}),JSON.stringify(winery),JSON.stringify({base_servicio_intermediacion:this.money(group.commissionCents),tratamiento_iva:'pendiente_validacion_fiscal_externa',total_retenido:this.money(group.commissionCents),porcentaje_comision:group.commissionRate}),'Factura de comisión de intermediación. Su tratamiento de IVA queda sometido a la validación fiscal externa y a los datos fiscales verificados de ambas partes antes de producción.']);}
  private async nextNumber(client:PoolClient,type:'justificante_cliente'|'liquidacion_bodega'|'factura_comision',prefix:'REC'|'LIQ'|'FAC'):Promise<string>{const year=new Date().getUTCFullYear();const rows=await client.query<{ultimo_numero:string}>(`INSERT INTO serie_documental(tipo,ejercicio,ultimo_numero) VALUES($1,$2,1) ON CONFLICT(tipo,ejercicio) DO UPDATE SET ultimo_numero=serie_documental.ultimo_numero+1,updated_at=now() RETURNING ultimo_numero::text`,[type,year]);const value=rows.rows[0]?.ultimo_numero;if(value===undefined)throw new Error('No se pudo asignar numeración documental.');return`${prefix}-${String(year)}-${value.padStart(8,'0')}`;}
  private ack(event:string,status:WebhookAck['status'],order:string,payment:WebhookAck['pago_estado'],orderState:WebhookAck['pedido_estado']):WebhookAck{return{event_id:event,status,pedido_id:order,...(payment===undefined?{}:{pago_estado:payment}),...(orderState===undefined?{}:{pedido_estado:orderState})};}
  private cents(value:string):number{const match=/^(\d+)\.(\d{2})$/.exec(value);if(match===null)throw new Error('Importe monetario inválido.');return Number(match[1])*100+Number(match[2]);}
  private money(cents:number):string{return`${String(Math.floor(cents/100))}.${String(cents%100).padStart(2,'0')}`;}
}
