import { createHmac, timingSafeEqual } from 'node:crypto';
import { BadRequestException, ConflictException, Injectable, NotFoundException, UnprocessableEntityException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { isUUID } from 'class-validator';
import { STRIPE_EVENT_TYPES, type StripeEventType, type StripeWebhookEvent, type WebhookAck } from './dto/stripe-webhook.dto.js';
import { StripeWebhookRepository } from './stripe-webhook.repository.js';

@Injectable()
export class StripeWebhookService {
  private readonly secret:string;private readonly livemode:boolean;
  constructor(private readonly repository:StripeWebhookRepository,config:ConfigService){this.secret=config.getOrThrow<string>('STRIPE_WEBHOOK_SECRET');this.livemode=config.getOrThrow<string>('STRIPE_SECRET_KEY').startsWith('sk_live_');}
  procesar(rawBody:Buffer|undefined,signature:string|undefined):Promise<WebhookAck>{if(rawBody===undefined||signature===undefined||!this.validSignature(rawBody,signature))throw new BadRequestException({code:'VALIDATION_ERROR',message:'Firma Stripe inválida o ausente.'});const event=this.parse(rawBody);return this.apply(event);}
  private async apply(event:StripeWebhookEvent):Promise<WebhookAck>{if(event.livemode!==this.livemode)throw new ConflictException({code:'CONFLICT',message:'El modo Stripe no coincide con el entorno.'});const metadata=event.data.object.metadata;const pedidoId=this.metadata(metadata,'pedido_id'),pagoId=this.metadata(metadata,'pago_id'),currency=this.metadata(metadata,'currency'),amount=this.metadata(metadata,'amount_cents'),signature=this.metadata(metadata,'metadata_signature');if(!isUUID(pedidoId)||!isUUID(pagoId)||currency!=='eur'||amount!==String(event.data.object.amount_total)||!this.validMetadata(pedidoId,pagoId,currency,amount,signature))throw new ConflictException({code:'CONFLICT',message:'La metadata Stripe no coincide con la sesión emitida.'});const result=await this.repository.procesar(event,pedidoId,pagoId);if(result.kind==='missing')throw new NotFoundException({code:'RESOURCE_NOT_FOUND',message:'Pedido o pago no encontrado.'});if(result.kind==='conflict')throw new ConflictException({code:'CONFLICT',message:result.message});return result.ack;}
  private parse(raw:Buffer):StripeWebhookEvent{let value:unknown;try{value=JSON.parse(raw.toString('utf8')) as unknown;}catch{throw new BadRequestException({code:'VALIDATION_ERROR',message:'Body Stripe inválido.'});}if(typeof value!=='object'||value===null)throw new BadRequestException({code:'VALIDATION_ERROR',message:'Evento Stripe inválido.'});const event=value as Record<string,unknown>;if(typeof event.type!=='string'||!STRIPE_EVENT_TYPES.includes(event.type as StripeEventType))throw new UnprocessableEntityException({code:'UNSUPPORTED_STRIPE_EVENT',message:'Tipo de evento Stripe no soportado.'});const data=event.data,obj=typeof data==='object'&&data!==null?(data as Record<string,unknown>).object:undefined;if(typeof event.id!=='string'||event.id.length<1||event.id.length>200||typeof event.livemode!=='boolean'||typeof obj!=='object'||obj===null)throw new BadRequestException({code:'VALIDATION_ERROR',message:'Evento Stripe incompleto.'});const session=obj as Record<string,unknown>;if(typeof session.id!=='string'||session.id.length<1||session.id.length>200||!['paid','unpaid','no_payment_required'].includes(String(session.payment_status))||!Number.isSafeInteger(session.amount_total)||Number(session.amount_total)<0||typeof session.currency!=='string'||typeof session.metadata!=='object'||session.metadata===null)throw new BadRequestException({code:'VALIDATION_ERROR',message:'Sesión Stripe incompleta.'});return{id:event.id,type:event.type as StripeEventType,livemode:event.livemode,data:{object:{id:session.id,payment_status:session.payment_status as StripeWebhookEvent['data']['object']['payment_status'],amount_total:Number(session.amount_total),currency:session.currency,metadata:session.metadata as Record<string,unknown>}}};}
  private validSignature(body:Buffer,header:string):boolean{const parts=header.split(',');const timestamp=parts.find(part=>part.startsWith('t='))?.slice(2);const signatures=parts.filter(part=>part.startsWith('v1=')).map(part=>part.slice(3));if(timestamp===undefined||!/^\d+$/.test(timestamp)||signatures.length===0)return false;const seconds=Number(timestamp),now=Math.floor(Date.now()/1000);if(!Number.isSafeInteger(seconds)||Math.abs(now-seconds)>300)return false;const expected=createHmac('sha256',this.secret).update(`${timestamp}.`).update(body).digest();return signatures.some(candidate=>{if(!/^[0-9a-fA-F]{64}$/.test(candidate))return false;return timingSafeEqual(expected,Buffer.from(candidate,'hex'));});}
  private validMetadata(order:string,payment:string,currency:string,amount:string,signature:string):boolean{if(!/^[0-9a-fA-F]{64}$/.test(signature))return false;const expected=createHmac('sha256',this.secret).update([order,payment,currency,amount].join('|')).digest();return timingSafeEqual(expected,Buffer.from(signature,'hex'));}
  private metadata(value:Record<string,unknown>,key:string):string{const field=value[key];return typeof field==='string'?field:'';}
}
