import { Injectable } from '@nestjs/common';
import type { PoolClient } from 'pg';
import { DatabaseService } from '../../common/database/database.service.js';
import type { StripeWebhookEvent, WebhookAck } from './dto/stripe-webhook.dto.js';

export type WebhookResult={kind:'ok';ack:WebhookAck}|{kind:'missing'}|{kind:'conflict';message:string};
interface PaymentRow { id:string;pedido_id:string;estado:WebhookAck['pago_estado'];stripe_checkout_session_id:string|null;total_cobrado:string }
interface OrderRow { id:string;carrito_id:string;estado:WebhookAck['pedido_estado'];subtotal:string;gastos_envio:string;impuestos:string;descuentos:string;total:string }
interface CartLine { id:string;vino_id:string;cantidad:number;precio_unitario:string;importe_total:string;bodega_id:string;nombre_vino:string;anada:number|null;stock_disponible:number;bodega_nombre:string;comision:string|null }
interface Group { bodegaId:string;bodegaName:string;commissionRate:string;subtotalCents:number;lines:CartLine[];shippingCents:number;taxCents:number;totalCents:number;commissionCents:number }
class MaterializationConflictError extends Error {}

@Injectable()
export class StripeWebhookRepository {
  constructor(private readonly database:DatabaseService){}
  async procesar(event:StripeWebhookEvent,pedidoId:string,pagoId:string):Promise<WebhookResult>{try{return await this.database.withTransaction(async client=>{
    const payments=await client.query<PaymentRow>(`SELECT id,pedido_id,estado,stripe_checkout_session_id,total_cobrado::text FROM pago WHERE id=$1 FOR UPDATE`,[pagoId]);const payment=payments.rows[0];if(payment===undefined)return{kind:'missing'};
    const orders=await client.query<OrderRow>(`SELECT id,carrito_id,estado,subtotal::text,gastos_envio::text,impuestos::text,descuentos::text,total::text FROM pedido WHERE id=$1 FOR UPDATE`,[pedidoId]);const order=orders.rows[0];if(order===undefined)return{kind:'missing'};if(payment.pedido_id!==pedidoId)return{kind:'conflict',message:'La relación Pedido–Pago no coincide con la metadata.'};
    if(this.cents(payment.total_cobrado)!==event.data.object.amount_total||event.data.object.currency!=='eur')return{kind:'conflict',message:'El importe o moneda no coincide con el Pago.'};
    const ledger=await client.query<{stripe_event_id:string}>(`INSERT INTO evento_webhook_stripe(stripe_event_id,tipo_evento,pago_id,procesado_at,resultado) VALUES($1,$2,$3,now(),'correcto') ON CONFLICT(stripe_event_id) DO NOTHING RETURNING stripe_event_id`,[event.id,event.type,pagoId]);
    if(ledger.rows[0]===undefined)return{kind:'ok',ack:this.ack(event.id,'duplicate',pedidoId,payment.estado,order.estado)};
    const success=event.type==='checkout.session.async_payment_succeeded'||(event.type==='checkout.session.completed'&&event.data.object.payment_status==='paid');
    if(success)return this.confirm(client,event,order,payment);
    if(event.type==='checkout.session.completed')return{kind:'ok',ack:this.ack(event.id,'ignored',pedidoId,payment.estado,order.estado)};
    if(event.data.object.id!==payment.stripe_checkout_session_id||payment.estado==='pagado')return{kind:'ok',ack:this.ack(event.id,'ignored',pedidoId,payment.estado,order.estado)};
    const state=event.type==='checkout.session.async_payment_failed'?'fallido':'cancelado';await client.query(`UPDATE pago SET estado=$2,updated_at=now() WHERE id=$1`,[payment.id,state]);await client.query(`INSERT INTO auditoria(tipo_entidad,entidad_id,accion,valor_anterior,valor_nuevo,descripcion,sistema) VALUES('pago',$1,'webhook_stripe',jsonb_build_object('estado',$2::text),jsonb_build_object('estado',$3::text),'Evento negativo Stripe validado','stripe')`,[payment.id,payment.estado,state]);return{kind:'ok',ack:this.ack(event.id,'processed',pedidoId,state,order.estado)};
  });}catch(error){if(error instanceof MaterializationConflictError)return{kind:'conflict',message:error.message};throw error;}}
  private async confirm(client:PoolClient,event:StripeWebhookEvent,order:OrderRow,payment:PaymentRow):Promise<WebhookResult>{const existing=await client.query<{total:number}>('SELECT count(*)::int total FROM pedido_item WHERE pedido_id=$1',[order.id]);if(payment.estado==='pagado'&&order.estado==='pagado'&&existing.rows[0]?.total!==0)return{kind:'ok',ack:this.ack(event.id,'processed',order.id,'pagado','pagado')};if(order.estado!=='pendiente_pago'||existing.rows[0]?.total!==0)throw new MaterializationConflictError('El Pedido no admite confirmación o está materializado de forma incoherente.');
    const lines=await client.query<CartLine>(`SELECT ci.id,ci.vino_id,ci.cantidad,ci.precio_unitario::text,ci.importe_total::text,v.bodega_id,v.nombre_comercial nombre_vino,v.anada,v.stock_disponible,b.nombre_comercial bodega_nombre,b.comision::text FROM carrito_item ci JOIN vino v ON v.id=ci.vino_id JOIN bodega b ON b.id=v.bodega_id WHERE ci.carrito_id=$1 ORDER BY v.id FOR UPDATE OF v`,[order.carrito_id]);if(lines.rows.length===0)throw new MaterializationConflictError('El carrito confirmado no contiene líneas.');for(const line of lines.rows){if(line.stock_disponible<line.cantidad)throw new MaterializationConflictError('Stock insuficiente para materializar el Pedido pagado.');if(line.comision===null)throw new MaterializationConflictError('La bodega no tiene comisión económica configurada.');}
    const groups=this.groups(lines.rows,order);let commission=0;for(const group of groups){const sub=await client.query<{id:string}>(`INSERT INTO subpedido(pedido_id,bodega_id,pago_id,subtotal,gastos_envio,impuestos,comision_marketplace,total,estado) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'pendiente') RETURNING id`,[order.id,group.bodegaId,payment.id,this.money(group.subtotalCents),this.money(group.shippingCents),this.money(group.taxCents),this.money(group.commissionCents),this.money(group.totalCents)]);const subId=sub.rows[0]?.id;if(subId===undefined)throw new Error('No se pudo crear el SubPedido.');for(const line of group.lines){const stock=await client.query<{id:string}>(`UPDATE vino SET stock_disponible=stock_disponible-$2,updated_at=now() WHERE id=$1 AND stock_disponible >= $2 RETURNING id`,[line.vino_id,line.cantidad]);if(stock.rows[0]===undefined)throw new MaterializationConflictError('Stock insuficiente para materializar el Pedido pagado.');await client.query(`INSERT INTO pedido_item(pedido_id,subpedido_id,vino_id,bodega_id,nombre_vino_snapshot,anada_snapshot,bodega_snapshot,precio_unitario,cantidad,importe_total,estado) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'normal')`,[order.id,subId,line.vino_id,group.bodegaId,line.nombre_vino,line.anada,group.bodegaName,line.precio_unitario,line.cantidad,line.importe_total]);}commission+=group.commissionCents;}
    await client.query(`UPDATE pago SET estado='pagado',referencia_stripe=$2,metodo_pago='stripe',comision_marketplace=$3,fecha_autorizacion=coalesce(fecha_autorizacion,now()),fecha_captura=coalesce(fecha_captura,now()),updated_at=now() WHERE id=$1`,[payment.id,event.data.object.id,this.money(commission)]);await client.query(`UPDATE pedido SET estado='pagado',updated_at=now() WHERE id=$1`,[order.id]);await client.query(`UPDATE carrito SET estado='convertido',fecha_conversion=coalesce(fecha_conversion,now()),updated_at=now() WHERE id=$1`,[order.carrito_id]);await client.query(`INSERT INTO auditoria(tipo_entidad,entidad_id,accion,valor_anterior,valor_nuevo,descripcion,sistema) VALUES('pedido',$1,'pago_confirmado',jsonb_build_object('estado',$2::text),jsonb_build_object('estado','pagado','stripe_event_id',$3::text),'Pago confirmado y pedido materializado; reparto pendiente de transferencia','stripe')`,[order.id,order.estado,event.id]);return{kind:'ok',ack:this.ack(event.id,'processed',order.id,'pagado','pagado')};}
  private groups(lines:CartLine[],order:OrderRow):Group[]{const map=new Map<string,Group>();for(const line of lines){const found=map.get(line.bodega_id);if(found===undefined)map.set(line.bodega_id,{bodegaId:line.bodega_id,bodegaName:line.bodega_nombre,commissionRate:line.comision??'0',subtotalCents:this.cents(line.importe_total),lines:[line],shippingCents:0,taxCents:0,totalCents:0,commissionCents:0});else{found.lines.push(line);found.subtotalCents+=this.cents(line.importe_total);}}const groups=[...map.values()].sort((a,b)=>a.bodegaId.localeCompare(b.bodegaId));this.allocate(groups,this.cents(order.gastos_envio),'shippingCents');this.allocate(groups,this.cents(order.impuestos),'taxCents');this.allocate(groups,this.cents(order.total),'totalCents');for(const group of groups)group.commissionCents=Math.min(group.totalCents,Math.round(group.subtotalCents*Number(group.commissionRate)/100));return groups;}
  private allocate(groups:Group[],amount:number,key:'shippingCents'|'taxCents'|'totalCents'):void{const base=groups.reduce((sum,group)=>sum+group.subtotalCents,0);let assigned=0;groups.forEach((group,index)=>{const value=index===groups.length-1?amount-assigned:Math.floor(amount*group.subtotalCents/base);group[key]=value;assigned+=value;});}
  private ack(event:string,status:WebhookAck['status'],order:string,payment:WebhookAck['pago_estado'],orderState:WebhookAck['pedido_estado']):WebhookAck{return{event_id:event,status,pedido_id:order,...(payment===undefined?{}:{pago_estado:payment}),...(orderState===undefined?{}:{pedido_estado:orderState})};}
  private cents(value:string):number{const match=/^(\d+)\.(\d{2})$/.exec(value);if(match===null)throw new Error('Importe monetario inválido.');return Number(match[1])*100+Number(match[2]);}
  private money(cents:number):string{return`${String(Math.floor(cents/100))}.${String(cents%100).padStart(2,'0')}`;}
}
