'use client';
import { useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import type { FormEvent } from 'react';
import type { ImageSummary, WineImageContentType } from '@/lib/winery/contracts';
import { authorizeImageUploadAction, confirmImageUploadAction, deleteImageAction, updateImageAction } from '@/app/(winery)/bodega/image-actions';

const MAX_BYTES=10*1024*1024;
const allowed=new Set<WineImageContentType>(['image/jpeg','image/png','image/webp']);
function bytesToBase64(buffer:ArrayBuffer):string{let binary='';for(const byte of new Uint8Array(buffer))binary+=String.fromCharCode(byte);return btoa(binary)}
function safeUploadUrl(value:string):string|undefined{try{const url=new URL(value);if(url.protocol==='https:'||(url.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(url.hostname)))return url.toString()}catch{}return undefined}
function messageWithReference(message:string|undefined,requestId:string|undefined):string{return `${message??'No se ha podido completar la operación.'}${requestId===undefined?'':` Referencia: ${requestId}`}`}

export function WineryImageManager({wineId,images}:{wineId:string;images:ImageSummary[]}){
  const router=useRouter(),fileInput=useRef<HTMLInputElement>(null);const [notice,setNotice]=useState<{kind:'error'|'success';text:string}>();const [pending,setPending]=useState(false);
  async function upload(event:FormEvent<HTMLFormElement>):Promise<void>{event.preventDefault();const uploadForm=event.currentTarget,form=new FormData(uploadForm),file=fileInput.current?.files?.[0],alt=String(form.get('alt_text')??'').trim(),order=Number(form.get('orden')??0),principal=form.get('es_principal')==='on';
    if(file===undefined||!allowed.has(file.type as WineImageContentType)||file.size<1||file.size>MAX_BYTES||alt.length<1||alt.length>500||!Number.isInteger(order)||order<0||order>999){setNotice({kind:'error',text:'Selecciona una imagen JPEG, PNG o WebP de hasta 10 MiB y completa sus metadatos.'});return}
    setPending(true);setNotice(undefined);try{const checksum=bytesToBase64(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),uploadId=crypto.randomUUID();const authorization=await authorizeImageUploadAction(wineId,{upload_id:uploadId,nombre_archivo:file.name.slice(0,200),content_type:file.type as WineImageContentType,tamanio_bytes:file.size,checksum_sha256:checksum});
      if(!authorization.ok||authorization.data===undefined){setNotice({kind:'error',text:messageWithReference(authorization.message,authorization.requestId)});return}const url=safeUploadUrl(authorization.data.upload_url);if(url===undefined){setNotice({kind:'error',text:'La API devolvió un destino de carga no seguro.'});return}
      const uploaded=await fetch(url,{method:authorization.data.method,headers:authorization.data.required_headers,body:file});if(!uploaded.ok&&uploaded.status!==412){setNotice({kind:'error',text:`El almacenamiento rechazó la carga (${uploaded.status}).`});return}
      const confirmed=await confirmImageUploadAction(wineId,{upload_id:uploadId,confirmation_token:authorization.data.confirmation_token,alt_text:alt,orden:order,es_principal:principal});if(!confirmed.ok){setNotice({kind:'error',text:messageWithReference(confirmed.message,confirmed.requestId)});return}uploadForm.reset();setNotice({kind:'success',text:'Imagen cargada y verificada correctamente.'});router.refresh();
    }catch{setNotice({kind:'error',text:'La carga se ha interrumpido. Puedes volver a intentarlo.'})}finally{setPending(false)}}
  async function update(event:FormEvent<HTMLFormElement>,imageId:string):Promise<void>{event.preventDefault();const form=new FormData(event.currentTarget),alt=String(form.get('alt_text')??'').trim(),order=Number(form.get('orden')??0);setPending(true);setNotice(undefined);try{const result=await updateImageAction(wineId,imageId,{alt_text:alt,orden:order,es_principal:form.get('es_principal')==='on'});if(!result.ok){setNotice({kind:'error',text:messageWithReference(result.message,result.requestId)});return}setNotice({kind:'success',text:'Metadatos actualizados.'});router.refresh()}catch{setNotice({kind:'error',text:'No se ha podido contactar con el servidor.'})}finally{setPending(false)}}
  async function remove(imageId:string):Promise<void>{if(!window.confirm('¿Desactivar esta imagen?'))return;setPending(true);setNotice(undefined);try{const result=await deleteImageAction(wineId,imageId);if(!result.ok){setNotice({kind:'error',text:messageWithReference(result.message,result.requestId)});return}setNotice({kind:'success',text:'Imagen desactivada.'});router.refresh()}catch{setNotice({kind:'error',text:'No se ha podido contactar con el servidor.'})}finally{setPending(false)}}
  return <section className="image-management"><div className="image-management-heading"><div><h2>Imágenes</h2><p>La imagen se carga directamente al almacenamiento y se confirma tras verificar tamaño, tipo y checksum.</p></div><span>{images.length} activas</span></div>{notice&&<div className={`form-status form-${notice.kind}`} role={notice.kind==='error'?'alert':'status'}><p>{notice.text}</p></div>}<form className="image-upload-form" onSubmit={upload}><label className="field field-wide">Archivo<input accept="image/jpeg,image/png,image/webp" disabled={pending} name="file" ref={fileInput} required type="file"/></label><label className="field field-wide">Texto alternativo<input disabled={pending} maxLength={500} name="alt_text" required/></label><label className="field">Orden<input defaultValue={images.length} disabled={pending} max={999} min={0} name="orden" required type="number"/></label><label className="check-field"><input disabled={pending} name="es_principal" type="checkbox"/>Imagen principal</label><button className="button primary" disabled={pending} type="submit">{pending?'Procesando…':'Subir y confirmar'}</button></form>{images.length===0?<p>Aún no hay imágenes confirmadas.</p>:<div className="image-admin-list">{images.map(image=><article className="image-admin-card" key={image.id}><Image alt={image.alt_text} height={320} src={image.url} unoptimized width={320}/><form onSubmit={event=>update(event,image.id)}><label className="field">Texto alternativo<input defaultValue={image.alt_text} disabled={pending} maxLength={500} name="alt_text" required/></label><label className="field">Orden<input defaultValue={image.orden} disabled={pending} max={999} min={0} name="orden" required type="number"/></label><label className="check-field"><input defaultChecked={image.es_principal} disabled={pending} name="es_principal" type="checkbox"/>Principal</label><div className="image-actions"><button className="button secondary" disabled={pending} type="submit">Guardar</button><button className="text-button" disabled={pending} onClick={()=>remove(image.id)} type="button">Desactivar</button></div></form></article>)}</div>}</section>
}
