import type { Locale } from './config';

const es = {
  skip: 'Saltar al contenido', nav: 'Navegación principal', wines: 'Vinos', wineries: 'Bodegas', wineryAccess: 'Soy bodega', signIn: 'Iniciar sesión', account: 'Mi cuenta', wineryPanel: 'Panel de bodega', admin: 'Administración', menu: 'Menú', openMenu: 'Abrir navegación', language: 'Idioma', home: 'Teralya, inicio', cart: 'Carrito',
  heroEyebrow: 'Directo de la bodega a tu casa', heroTitle: 'El vino que eliges.', heroEm: 'La historia que recibes.', heroCopy: 'Descubre vinos europeos con identidad, compra directamente a quienes los elaboran y recíbelos en casa sin cargar cajas ni pasar por intermediarios.', discoverWines: 'Descubrir vinos', meetWineries: 'Conocer las bodegas', originTable: 'Del origen a tu mesa', originTableCopy: 'Seleccionado por ti. Enviado por la bodega.', advantages: 'Ventajas de Teralya', direct: 'Directo de bodega', directCopy: 'Compra a quien elabora', european: 'Selección europea', europeanCopy: 'Vinos con origen e identidad', delivery: 'Entrega en casa', deliveryCopy: 'Sin cargar con las cajas', protected: 'Pago protegido', protectedCopy: 'Compra segura con Stripe', selection: 'Nuestra selección', recommended: 'Vinos recomendados', recommendedBadge: 'Recomendado', teralyaSelection: 'Selección Teralya', seeWine: 'Ver vino', seeAll: 'Ver todos los vinos', closer: 'Más cerca del origen', storyTitle: 'De su bodega.', storyEm: 'A tu momento.', storyCopy: 'Cada botella lleva consigo un lugar, una familia y una forma de entender el vino. Teralya te acerca a esas historias y hace que recibirlas sea sencillo.', personal: 'Una elección personal.', special: 'Una entrega especial.', womanWine: 'Mujer disfrutando una copa de vino en casa', makeWine: '¿Elaboras vino?', joinTitle: 'Tu bodega también puede formar parte de Teralya.', joinCopy: 'Presenta tus vinos con identidad y vende directamente a quienes valoran el origen.', forWineries: 'Teralya para bodegas',
  footerClaim: 'Vinos europeos vendidos directamente por sus bodegas.', explore: 'Explorar', legal: 'Legal', terms: 'Términos y condiciones', privacy: 'Privacidad', cookies: 'Cookies', refunds: 'Reembolsos', withdrawal: 'Desistimiento', age: 'Mayoría de edad', rights: 'Todos los derechos reservados.',
} as const;

type Messages = { [K in keyof typeof es]: string };

const en: Messages = {skip:'Skip to content',nav:'Main navigation',wines:'Wines',wineries:'Wineries',wineryAccess:'I am a winery',signIn:'Sign in',account:'My account',wineryPanel:'Winery dashboard',admin:'Administration',menu:'Menu',openMenu:'Open navigation',language:'Language',home:'Teralya, home',cart:'Cart',heroEyebrow:'Direct from the winery to your home',heroTitle:'The wine you choose.',heroEm:'The story you receive.',heroCopy:'Discover European wines with identity, buy directly from their makers and receive them at home without carrying boxes or intermediaries.',discoverWines:'Discover wines',meetWineries:'Meet the wineries',originTable:'From its origin to your table',originTableCopy:'Selected by you. Shipped by the winery.',advantages:'Teralya benefits',direct:'Direct from the winery',directCopy:'Buy from the producer',european:'European selection',europeanCopy:'Wines with origin and identity',delivery:'Home delivery',deliveryCopy:'No boxes to carry',protected:'Protected payment',protectedCopy:'Secure checkout with Stripe',selection:'Our selection',recommended:'Recommended wines',recommendedBadge:'Recommended',teralyaSelection:'Teralya selection',seeWine:'View wine',seeAll:'View all wines',closer:'Closer to the origin',storyTitle:'From their winery.',storyEm:'To your moment.',storyCopy:'Every bottle carries a place, a family and a way of understanding wine. Teralya brings you closer to those stories and makes receiving them simple.',personal:'A personal choice.',special:'A special delivery.',womanWine:'Woman enjoying a glass of wine at home',makeWine:'Do you make wine?',joinTitle:'Your winery can also be part of Teralya.',joinCopy:'Present your wines with identity and sell directly to people who value their origin.',forWineries:'Teralya for wineries',footerClaim:'European wines sold directly by their wineries.',explore:'Explore',legal:'Legal',terms:'Terms and conditions',privacy:'Privacy',cookies:'Cookies',refunds:'Refunds',withdrawal:'Right of withdrawal',age:'Legal drinking age',rights:'All rights reserved.'};
const fr: Messages = {skip:'Aller au contenu',nav:'Navigation principale',wines:'Vins',wineries:'Domaines',wineryAccess:'Je suis un domaine',signIn:'Se connecter',account:'Mon compte',wineryPanel:'Espace domaine',admin:'Administration',menu:'Menu',openMenu:'Ouvrir la navigation',language:'Langue',home:'Teralya, accueil',cart:'Panier',heroEyebrow:'Directement du domaine à votre domicile',heroTitle:'Le vin que vous choisissez.',heroEm:'L’histoire que vous recevez.',heroCopy:'Découvrez des vins européens de caractère, achetez directement auprès de ceux qui les élaborent et recevez-les chez vous, sans cartons à porter ni intermédiaires.',discoverWines:'Découvrir les vins',meetWineries:'Découvrir les domaines',originTable:'De l’origine à votre table',originTableCopy:'Choisi par vous. Expédié par le domaine.',advantages:'Les avantages Teralya',direct:'Direct du domaine',directCopy:'Achetez auprès du producteur',european:'Sélection européenne',europeanCopy:'Des vins avec une origine et une identité',delivery:'Livraison à domicile',deliveryCopy:'Aucun carton à porter',protected:'Paiement protégé',protectedCopy:'Paiement sécurisé avec Stripe',selection:'Notre sélection',recommended:'Vins recommandés',recommendedBadge:'Recommandé',teralyaSelection:'Sélection Teralya',seeWine:'Voir le vin',seeAll:'Voir tous les vins',closer:'Au plus près de l’origine',storyTitle:'De leur domaine.',storyEm:'À votre moment.',storyCopy:'Chaque bouteille porte un lieu, une famille et une manière de comprendre le vin. Teralya vous rapproche de ces histoires et simplifie leur livraison.',personal:'Un choix personnel.',special:'Une livraison spéciale.',womanWine:'Femme dégustant un verre de vin chez elle',makeWine:'Vous élaborez du vin ?',joinTitle:'Votre domaine peut aussi rejoindre Teralya.',joinCopy:'Présentez vos vins avec leur identité et vendez directement à ceux qui attachent de l’importance à leur origine.',forWineries:'Teralya pour les domaines',footerClaim:'Des vins européens vendus directement par leurs domaines.',explore:'Explorer',legal:'Informations légales',terms:'Conditions générales',privacy:'Confidentialité',cookies:'Cookies',refunds:'Remboursements',withdrawal:'Droit de rétractation',age:'Majorité légale',rights:'Tous droits réservés.'};
const de: Messages = {skip:'Zum Inhalt springen',nav:'Hauptnavigation',wines:'Weine',wineries:'Weingüter',wineryAccess:'Ich bin ein Weingut',signIn:'Anmelden',account:'Mein Konto',wineryPanel:'Weingut-Dashboard',admin:'Verwaltung',menu:'Menü',openMenu:'Navigation öffnen',language:'Sprache',home:'Teralya, Startseite',cart:'Warenkorb',heroEyebrow:'Direkt vom Weingut zu Ihnen nach Hause',heroTitle:'Der Wein, den Sie wählen.',heroEm:'Die Geschichte, die Sie erhalten.',heroCopy:'Entdecken Sie charaktervolle europäische Weine, kaufen Sie direkt bei den Erzeugern und lassen Sie sie bequem und ohne Zwischenhändler nach Hause liefern.',discoverWines:'Weine entdecken',meetWineries:'Weingüter kennenlernen',originTable:'Vom Ursprung auf Ihren Tisch',originTableCopy:'Von Ihnen gewählt. Vom Weingut versandt.',advantages:'Vorteile von Teralya',direct:'Direkt vom Weingut',directCopy:'Beim Erzeuger kaufen',european:'Europäische Auswahl',europeanCopy:'Weine mit Herkunft und Identität',delivery:'Lieferung nach Hause',deliveryCopy:'Keine Kisten tragen',protected:'Geschützte Zahlung',protectedCopy:'Sicher bezahlen mit Stripe',selection:'Unsere Auswahl',recommended:'Empfohlene Weine',recommendedBadge:'Empfohlen',teralyaSelection:'Teralya-Auswahl',seeWine:'Wein ansehen',seeAll:'Alle Weine ansehen',closer:'Näher am Ursprung',storyTitle:'Von ihrem Weingut.',storyEm:'Zu Ihrem Moment.',storyCopy:'Jede Flasche trägt einen Ort, eine Familie und eine besondere Auffassung von Wein in sich. Teralya bringt Ihnen diese Geschichten näher und macht die Lieferung einfach.',personal:'Eine persönliche Wahl.',special:'Eine besondere Lieferung.',womanWine:'Frau genießt zu Hause ein Glas Wein',makeWine:'Erzeugen Sie Wein?',joinTitle:'Auch Ihr Weingut kann Teil von Teralya werden.',joinCopy:'Präsentieren Sie Ihre Weine mit Identität und verkaufen Sie direkt an Menschen, die Herkunft schätzen.',forWineries:'Teralya für Weingüter',footerClaim:'Europäische Weine direkt von ihren Weingütern verkauft.',explore:'Entdecken',legal:'Rechtliches',terms:'Allgemeine Geschäftsbedingungen',privacy:'Datenschutz',cookies:'Cookies',refunds:'Erstattungen',withdrawal:'Widerrufsrecht',age:'Volljährigkeit',rights:'Alle Rechte vorbehalten.'};

// Italian is explicit; the remaining launch locales inherit the complete English
// catalogue until their human-reviewed copy is loaded, so no Spanish leaks into them.
const it: Messages = {...en,wines:'Vini',wineries:'Cantine',signIn:'Accedi',account:'Il mio account',menu:'Menu',language:'Lingua',heroEyebrow:'Direttamente dalla cantina a casa tua',heroTitle:'Il vino che scegli.',heroEm:'La storia che ricevi.',discoverWines:'Scopri i vini',meetWineries:'Scopri le cantine',recommended:'Vini consigliati',recommendedBadge:'Consigliato',seeWine:'Vedi vino',seeAll:'Vedi tutti i vini',delivery:'Consegna a domicilio',protected:'Pagamento protetto',makeWine:'Produci vino?',forWineries:'Teralya per le cantine',legal:'Note legali',privacy:'Privacy',rights:'Tutti i diritti riservati.'};

export const messages: Readonly<Record<Locale, Messages>> = { es, en, fr, de, it, pt: en, el: en, hu: en, ro: en, hr: en, bg: en };
export type MessageKey = keyof Messages;
