import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AddToCart } from '@/components/add-to-cart';
import { formatEuro,getPublicWine,type WinePublicDetail } from '@/lib/api/catalog';
import { ApiProblem } from '@/lib/api/problem';
import { readSessionIdentity } from '@/lib/session/session';
interface Props{params:Promise<{id:string}>}
function Fact({label,value}:{label:string;value?:string|number}){return value===undefined?null:<div><dt>{label}</dt><dd>{value}</dd></div>}
function Failure({problem}:{problem?:ApiProblem}){return <main className="screen-state"><h1>No hemos podido cargar este vino</h1><p>Inténtalo de nuevo dentro de unos instantes.</p>{problem!==undefined&&<p className="request-reference">Referencia: {problem.problem.request_id}</p>}<Link className="button secondary" href="/vinos">Volver al catálogo</Link></main>}
export default async function WineDetailPage({params}:Props){const{id}=await params;const identity=await readSessionIdentity();let wine:WinePublicDetail;try{wine=await getPublicWine(id)}catch(error){if(error instanceof ApiProblem&&error.problem.status===404)notFound();return <Failure problem={error instanceof ApiProblem?error:undefined}/>}const hero=wine.imagen_principal??wine.imagenes[0];const origin=[wine.region,wine.denominacion_origen,wine.pais].filter(Boolean).join(' · ');return <main className="wine-detail"><nav aria-label="Migas de pan" className="breadcrumbs"><Link href="/vinos">Vinos</Link><span aria-hidden="true">/</span><span aria-current="page">{wine.nombre_comercial}</span></nav><section className="wine-hero"><div className="wine-detail-image">{hero===undefined?<span aria-hidden="true" className="image-placeholder">T</span>:<Image alt={hero.alt_text} fill priority sizes="(max-width: 800px) 100vw, 50vw" src={hero.url} unoptimized/>}</div><div className="wine-detail-intro"><p className="eyebrow">{wine.tipo_vino??'Vino de bodega'}</p><h1>{wine.nombre_comercial}</h1><p className="detail-winery">de {wine.bodega.nombre_comercial}</p>{origin!==''&&<p className="detail-origin">{origin}</p>}<p className="detail-price">{formatEuro(wine.precio)}</p>{wine.disponible_venta?<p className="availability available">Disponible</p>:<p className="availability unavailable">Temporalmente agotado</p>}{wine.descripcion_corta!==undefined&&<p className="detail-lead">{wine.descripcion_corta}</p>}<AddToCart authenticated={identity?.rol==='comprador'} available={wine.disponible_venta} wine={{id:wine.id,nombre:wine.nombre_comercial,bodega:wine.bodega.nombre_comercial,precio:wine.precio,...(hero===undefined?{}:{imagen_url:hero.url,imagen_alt:hero.alt_text})}}/></div></section><section className="wine-content"><div>{wine.descripcion_completa!==undefined&&<><h2>El vino</h2><p>{wine.descripcion_completa}</p></>}{wine.nota_cata!==undefined&&<><h2>Nota de cata</h2><p>{wine.nota_cata}</p></>}{wine.maridaje!==undefined&&<><h2>Maridaje</h2><p>{wine.maridaje}</p></>}</div><aside aria-labelledby="wine-facts-title" className="wine-facts"><h2 id="wine-facts-title">Ficha</h2><dl><Fact label="Añada" value={wine.anada}/><Fact label="Uvas" value={wine.variedades_uva?.join(', ')}/><Fact label="Crianza" value={wine.crianza}/><Fact label="Meses de crianza" value={wine.meses_crianza}/><Fact label="Graduación" value={wine.graduacion_alcoholica===undefined?undefined:`${wine.graduacion_alcoholica}%`}/><Fact label="Formato" value={wine.volumen_ml===undefined?undefined:`${wine.volumen_ml} ml`}/><Fact label="Servicio" value={wine.temperatura_servicio}/></dl></aside></section>{wine.imagenes.length>1&&<section aria-labelledby="gallery-title" className="wine-gallery"><h2 id="gallery-title">Galería</h2><div>{wine.imagenes.map(image=><figure key={image.id}><Image alt={image.alt_text} fill sizes="(max-width: 700px) 50vw, 25vw" src={image.url} unoptimized/></figure>)}</div></section>}</main>}
