import { BadRequestException,Injectable,NotFoundException } from '@nestjs/common';
import { isUUID } from 'class-validator';
import { CatalogRepository,type CatalogWineRecord } from './catalog.repository.js';
import type { CatalogQueryDto } from './dto/catalog-query.dto.js';
import type { PageWineSummary,WinePublicDetail,WineSummary } from './dto/catalog.dto.js';
import type { BodegaSummary,ImageSummary } from './dto/wine.dto.js';
@Injectable()
export class CatalogService{constructor(private readonly repository:CatalogRepository){}
 async listar(query:CatalogQueryDto):Promise<PageWineSummary>{if(query.precio_min!==undefined&&query.precio_max!==undefined&&Number(query.precio_min)>Number(query.precio_max))throw new BadRequestException({code:'VALIDATION_ERROR',message:'precio_min no puede ser superior a precio_max.'});const result=await this.repository.listar(query);return{items:result.items.map(row=>this.summary(row)),page:query.page,page_size:query.page_size,total_items:result.total,total_pages:Math.ceil(result.total/query.page_size)};}
 async obtener(id:string):Promise<WinePublicDetail>{if(!isUUID(id))this.notFound();const row=await this.repository.obtener(id);if(row===null)this.notFound();return this.detail(row);}
 private bodega(row:CatalogWineRecord):BodegaSummary{return{id:row.bodega_id,nombre_comercial:row.bodega_nombre,...this.optional(row,'bodega_slug','slug'),...this.optional(row,'bodega_logo_url','logo_url'),...this.optional(row,'bodega_region','region'),...this.optional(row,'bodega_pais','pais'),...this.optional(row,'bodega_denominacion_origen','denominacion_origen')};}
 private image(row:CatalogWineRecord['imagenes'][number]):ImageSummary{return{id:row.id,url:row.url,es_principal:row.es_principal,orden:row.orden,alt_text:row.alt_text,...(row.resolucion===null?{}:{resolucion:row.resolucion})};}
 private summary(row:CatalogWineRecord):WineSummary{const principal=row.imagenes.find(image=>image.es_principal);return{id:row.id,nombre_comercial:row.nombre_comercial,precio:row.precio,moneda:row.moneda,disponible_venta:row.disponible_venta,bodega:this.bodega(row),...this.optional(row,'slug'),...this.optional(row,'tipo_vino'),...this.optional(row,'anada'),...this.optional(row,'region'),...this.optional(row,'denominacion_origen'),...(principal===undefined?{}:{imagen_principal:this.image(principal)})};}
 private detail(row:CatalogWineRecord):WinePublicDetail{return{...this.summary(row),imagenes:row.imagenes.map(image=>this.image(image)),...this.optional(row,'pais'),...this.optional(row,'variedades_uva'),...this.optional(row,'crianza'),...this.optional(row,'meses_crianza'),...this.optional(row,'graduacion_alcoholica'),...this.optional(row,'volumen_ml'),...this.optional(row,'descripcion_corta'),...this.optional(row,'descripcion_completa'),...this.optional(row,'nota_cata'),...this.optional(row,'maridaje'),...this.optional(row,'temperatura_servicio'),...this.optional(row,'certificaciones'),...this.optional(row,'premios'),...this.optional(row,'produccion_limitada')};}
 private optional(row:CatalogWineRecord,key:keyof CatalogWineRecord,alias?:string):Record<string,unknown>{const value=row[key];return value===null?{}:{[alias??key]:value};}private notFound():never{throw new NotFoundException({code:'RESOURCE_NOT_FOUND',message:'Vino no encontrado.'});}}
