import { Injectable } from '@nestjs/common';
import { DatabaseService } from '../../common/database/database.service.js';
import type { CatalogQueryDto } from './dto/catalog-query.dto.js';
import type { ImageRecord } from './vinos.repository.js';
export interface CatalogWineRecord{id:string;bodega_id:string;nombre_comercial:string;slug:string|null;tipo_vino:string|null;anada:number|null;pais:string|null;region:string|null;denominacion_origen:string|null;variedades_uva:string[]|null;crianza:string|null;meses_crianza:number|null;graduacion_alcoholica:string|null;volumen_ml:number|null;descripcion_corta:string|null;descripcion_completa:string|null;nota_cata:string|null;maridaje:string|null;temperatura_servicio:string|null;certificaciones:string[]|null;premios:string[]|null;produccion_limitada:boolean|null;precio:string;moneda:'EUR';disponible_venta:boolean;bodega_nombre:string;bodega_slug:string|null;bodega_logo_url:string|null;bodega_region:string|null;bodega_pais:string|null;bodega_denominacion_origen:string|null;imagenes:ImageRecord[]}
export interface CatalogPage{items:CatalogWineRecord[];total:number}
const COLUMNS=`v.id,v.bodega_id,v.nombre_comercial,v.slug,v.tipo_vino,v.anada,v.pais,v.region,v.denominacion_origen,v.variedades_uva,v.crianza,v.meses_crianza,v.graduacion_alcoholica::text,v.volumen_ml,v.descripcion_corta,v.descripcion_completa,v.nota_cata,v.maridaje,v.temperatura_servicio,v.certificaciones,v.premios,v.produccion_limitada,v.precio::text,v.moneda,v.disponible_venta,b.nombre_comercial AS bodega_nombre,b.slug AS bodega_slug,b.logo_url AS bodega_logo_url,b.region AS bodega_region,b.pais AS bodega_pais,b.denominacion_origen AS bodega_denominacion_origen`;
@Injectable()
export class CatalogRepository{constructor(private readonly database:DatabaseService){}
 async listar(query:CatalogQueryDto):Promise<CatalogPage>{const params:unknown[]=[];const where=["v.estado='publicado'","v.disponible_venta=true",'v.stock_disponible>0',"b.estado IN ('aprobada','activa')"];const add=(sql:string,value:unknown)=>{params.push(value);where.push(sql.replace('?',`$${String(params.length)}`));};if(query.q!==undefined){params.push(`%${this.escape(query.q)}%`);const p=`$${String(params.length)}`;where.push(`(v.nombre_comercial ILIKE ${p} ESCAPE '\\' OR b.nombre_comercial ILIKE ${p} ESCAPE '\\')`);}if(query.tipo_vino!==undefined)add('v.tipo_vino=?',query.tipo_vino);if(query.region!==undefined)add('v.region=?',query.region);if(query.denominacion_origen!==undefined)add('v.denominacion_origen=?',query.denominacion_origen);if(query.precio_min!==undefined)add('v.precio>=?::numeric',query.precio_min);if(query.precio_max!==undefined)add('v.precio<=?::numeric',query.precio_max);const clause=where.join(' AND ');const count=await this.database.query<{total:string}>(`SELECT count(*)::text AS total FROM vino v JOIN bodega b ON b.id=v.bodega_id WHERE ${clause}`,params);params.push(query.page_size,(query.page-1)*query.page_size);const rows=await this.database.query<Omit<CatalogWineRecord,'imagenes'>>(`SELECT ${COLUMNS} FROM vino v JOIN bodega b ON b.id=v.bodega_id WHERE ${clause} ORDER BY v.fecha_publicacion DESC NULLS LAST,v.id DESC LIMIT $${String(params.length-1)} OFFSET $${String(params.length)}`,params);return{items:await this.images(rows),total:Number(count[0]?.total??0)};}
 async obtener(id:string):Promise<CatalogWineRecord|null>{const rows=await this.database.query<Omit<CatalogWineRecord,'imagenes'>>(`SELECT ${COLUMNS} FROM vino v JOIN bodega b ON b.id=v.bodega_id WHERE v.id=$1 AND v.estado='publicado' AND b.estado IN ('aprobada','activa')`,[id]);return(await this.images(rows))[0]??null;}
 private async images(rows:Omit<CatalogWineRecord,'imagenes'>[]):Promise<CatalogWineRecord[]>{if(rows.length===0)return[];const images=await this.database.query<ImageRecord&{entidad_id:string}>("SELECT id,entidad_id,url,es_principal,orden,alt_text,resolucion FROM imagen WHERE tipo_entidad='vino' AND entidad_id=ANY($1::uuid[]) AND activa=true ORDER BY es_principal DESC,orden,id",[rows.map(row=>row.id)]);return rows.map(row=>({...row,imagenes:images.filter(image=>image.entidad_id===row.id)}));}
 private escape(value:string):string{return value.replaceAll('\\','\\\\').replaceAll('%','\\%').replaceAll('_','\\_');}}
