import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { isUUID } from 'class-validator';
import type { SessionActor } from '../../common/security/session.service.js';
import type { WineOwnQueryDto, WineWriteRequestDto } from './dto/wine-request.dto.js';
import type { BodegaSummary, ImageSummary, PageWineOwnSummary, WineOwnDetail, WineOwnSummary } from './dto/wine.dto.js';
import { VinosRepository, type OwnedResult, type WineRecord } from './vinos.repository.js';

@Injectable()
export class VinosService {
  constructor(private readonly repository:VinosRepository){}
  async crear(actor:SessionActor,input:WineWriteRequestDto):Promise<WineOwnDetail>{const bodegaId=await this.operationalBodega(actor);return this.detail(await this.repository.crear(bodegaId,input));}
  async listar(actor:SessionActor,query:WineOwnQueryDto):Promise<PageWineOwnSummary>{const bodegaId=await this.operationalBodega(actor);const result=await this.repository.listar(bodegaId,query.estado,query.page,query.page_size);return{items:result.items.map(wine=>this.summary(wine)),page:query.page,page_size:query.page_size,total_items:result.total,total_pages:Math.ceil(result.total/query.page_size)};}
  async obtener(actor:SessionActor,id:string):Promise<WineOwnDetail>{this.validId(id);return this.detail(this.resolve(await this.repository.obtener(id,await this.operationalBodega(actor))));}
  async reemplazar(actor:SessionActor,id:string,input:WineWriteRequestDto):Promise<WineOwnDetail>{this.validId(id);return this.detail(this.resolve(await this.repository.reemplazar(id,await this.operationalBodega(actor),input)));}
  async solicitarPublicacion(actor:SessionActor,id:string):Promise<WineOwnDetail>{this.validId(id);const result=await this.repository.solicitarPublicacion(id,await this.operationalBodega(actor),actor.usuarioId);if(result.kind==='missing')this.notFound();if(result.kind==='conflict')throw new ConflictException({code:'CONFLICT',message:'El vino ya está publicado o pendiente de revisión.'});if(result.kind==='invalid')throw new BadRequestException({code:'VALIDATION_ERROR',message:'El vino o la bodega no cumplen los requisitos de publicación.'});return this.detail(result.wine);}
  private resolve(result:OwnedResult):WineRecord{if(result.kind==='missing')this.notFound();if(result.kind==='foreign')throw new ForbiddenException({code:'FORBIDDEN',message:'El vino pertenece a otra bodega.'});return result.wine;}
  private bodegaId(actor:SessionActor):string{if(actor.rol!=='bodega'||actor.bodegaId===undefined)throw new ForbiddenException({code:'FORBIDDEN',message:'La sesión no está asociada a una bodega.'});return actor.bodegaId;}
  private async operationalBodega(actor:SessionActor):Promise<string>{const id=this.bodegaId(actor);if(!await this.repository.bodegaPuedeOperar(id))throw new ForbiddenException({code:'FORBIDDEN',message:'La bodega no está validada para operar.'});return id;}
  private validId(id:string):void{if(!isUUID(id))this.notFound();}
  private notFound():never{throw new NotFoundException({code:'RESOURCE_NOT_FOUND',message:'Vino no encontrado.'});}
  private image(image:WineRecord['imagenes'][number]):ImageSummary{return{id:image.id,url:image.url,es_principal:image.es_principal,orden:image.orden,alt_text:image.alt_text,...(image.resolucion===null?{}:{resolucion:image.resolucion})};}
  private bodega(wine:WineRecord):BodegaSummary{return{id:wine.bodega_id,nombre_comercial:wine.bodega_nombre,...this.optional(wine,'bodega_slug','slug'),...this.optional(wine,'bodega_logo_url','logo_url'),...this.optional(wine,'bodega_region','region'),...this.optional(wine,'bodega_pais','pais'),...this.optional(wine,'bodega_denominacion_origen','denominacion_origen')};}
  private summary(wine:WineRecord):WineOwnSummary{const principal=wine.imagenes.find(image=>image.es_principal);return{id:wine.id,nombre_comercial:wine.nombre_comercial,estado:wine.estado,stock_disponible:wine.stock_disponible,disponible_venta:wine.disponible_venta,updated_at:this.iso(wine.updated_at),...this.optional(wine,'sku'),precio:wine.precio,moneda:wine.moneda,...(principal===undefined?{}:{imagen_principal:this.image(principal)})};}
  private detail(wine:WineRecord):WineOwnDetail{const principal=wine.imagenes.find(image=>image.es_principal);return{id:wine.id,nombre_comercial:wine.nombre_comercial,precio:wine.precio,moneda:wine.moneda,disponible_venta:wine.disponible_venta,bodega:this.bodega(wine),imagenes:wine.imagenes.map(image=>this.image(image)),estado:wine.estado,stock_disponible:wine.stock_disponible,stock_reservado:wine.stock_reservado,stock_minimo:wine.stock_minimo,created_at:this.iso(wine.created_at),updated_at:this.iso(wine.updated_at),...this.optional(wine,'slug'),...this.optional(wine,'sku'),...this.optional(wine,'tipo_vino'),...this.optional(wine,'anada'),...this.optional(wine,'pais'),...this.optional(wine,'region'),...this.optional(wine,'denominacion_origen'),...this.optional(wine,'variedades_uva'),...this.optional(wine,'crianza'),...this.optional(wine,'meses_crianza'),...this.optional(wine,'graduacion_alcoholica'),...this.optional(wine,'volumen_ml'),...this.optional(wine,'descripcion_corta'),...this.optional(wine,'descripcion_completa'),...this.optional(wine,'nota_cata'),...this.optional(wine,'maridaje'),...this.optional(wine,'temperatura_servicio'),...this.optional(wine,'certificaciones'),...this.optional(wine,'premios'),...this.optional(wine,'produccion_limitada'),...this.optional(wine,'peso_gramos'),...this.optional(wine,'plazo_preparacion_dias'),...this.optional(wine,'botellas_por_caja'),...(principal===undefined?{}:{imagen_principal:this.image(principal)})};}
  private optional(wine:WineRecord,key:keyof WineRecord,alias?:string):Record<string,unknown>{const value=wine[key];return value===null?{}:{[alias??key]:value};}
  private iso(value:Date|string):string{return new Date(value).toISOString();}
}
