'use server';
import { redirect,RedirectType } from 'next/navigation';
import type { Route } from 'next';
import { apiRequest } from '@/lib/api/client';
import { ApiProblem } from '@/lib/api/problem';
import { writeSession } from '@/lib/session/session';
import { destinationForRole,loginPayload,parseAuthSession,recoveryPayload,registerPayload,resetPayload,wineryRegisterPayload,type AuthFormState,type AuthSession,type GenericAck } from '@/lib/auth/contracts';
function problemState(error:unknown,fallback:string):AuthFormState{if(!(error instanceof ApiProblem))return{fieldErrors:{},formError:fallback};const fields:Record<string,string[]>={};for(const item of error.problem.field_errors??[])(fields[item.field]??=[]).push(item.message);const messages:Record<number,string>={401:'El correo o la contraseña no son correctos.',403:'Esta cuenta no puede acceder en este momento.',404:'El enlace no es válido o ha caducado.',409:'No se ha podido completar porque los datos ya están en uso o el enlace ya fue utilizado.',429:'Demasiados intentos. Espera unos minutos antes de volver a intentarlo.'};return{fieldErrors:fields,formError:Object.keys(fields).length===0?(messages[error.problem.status]??fallback):undefined,requestId:error.problem.request_id}}
async function establish(session:AuthSession):Promise<never>{const expires=new Date(Math.min(new Date(session.expires_at).getTime(),Date.now()+28_800_000));await writeSession(session.access_token,{usuario_id:session.usuario.id,rol:session.usuario.rol,...(session.usuario.bodega_id===undefined?{}:{bodega_id:session.usuario.bodega_id})},expires);redirect(destinationForRole(session.usuario.rol) as Route)}
export async function loginAction(_previous:AuthFormState,form:FormData):Promise<AuthFormState>{const parsed=loginPayload(form);if(parsed.value===undefined)return{fieldErrors:parsed.errors};let session:AuthSession;try{session=parseAuthSession(await apiRequest<unknown>('/auth/login',{method:'POST',body:parsed.value}))}catch(error){return problemState(error,'No se ha podido iniciar sesión.')}return establish(session)}
export async function registerAction(_previous:AuthFormState,form:FormData):Promise<AuthFormState>{const parsed=registerPayload(form);if(parsed.value===undefined)return{fieldErrors:parsed.errors};let session:AuthSession;try{session=parseAuthSession(await apiRequest<unknown>('/auth/registro/comprador',{method:'POST',body:parsed.value}))}catch(error){return problemState(error,'No se ha podido crear la cuenta.')}return establish(session)}
export async function wineryRegisterAction(_previous:AuthFormState,form:FormData):Promise<AuthFormState>{const parsed=wineryRegisterPayload(form);if(parsed.value===undefined)return{fieldErrors:parsed.errors};try{await apiRequest<unknown>('/bodegas',{method:'POST',body:parsed.value});return{fieldErrors:{},success:'Solicitud recibida. Revisaremos la bodega y activaremos su acceso profesional.'}}catch(error){return problemState(error,'No se ha podido registrar la bodega.')}}
export async function recoveryAction(_previous:AuthFormState,form:FormData):Promise<AuthFormState>{const parsed=recoveryPayload(form);if(parsed.value===undefined)return{fieldErrors:parsed.errors};try{await apiRequest<GenericAck>('/auth/recuperar-password',{method:'POST',body:parsed.value});return{fieldErrors:{},success:'Si existe una cuenta con ese correo, recibirás un enlace para restablecer la contraseña.'}}catch(error){return problemState(error,'No se ha podido procesar la solicitud.')}}
export async function resetAction(_previous:AuthFormState,form:FormData):Promise<AuthFormState>{const parsed=resetPayload(form);if(parsed.value===undefined)return{fieldErrors:parsed.errors};try{await apiRequest<GenericAck>('/auth/restablecer-password',{method:'POST',body:parsed.value})}catch(error){return problemState(error,'No se ha podido restablecer la contraseña.')}redirect('/acceso?password=restablecida' as Route,RedirectType.replace)}
