'use client';
import Link from 'next/link';
import type { Route } from 'next';
import { useActionState } from 'react';
import { useFormStatus } from 'react-dom';
import { initialAuthState,type AuthFormState } from '@/lib/auth/contracts';
import { loginAction,recoveryAction,registerAction,resetAction } from './actions';
function Errors({state,field}:{state:AuthFormState;field:string}){const messages=state.fieldErrors[field];return messages===undefined?null:<ul className="field-errors" id={`${field}-errors`}>{messages.map(message=><li key={message}>{message}</li>)}</ul>}
function Status({state}:{state:AuthFormState}){return <>{state.formError!==undefined&&<div className="form-status form-error" role="alert"><p>{state.formError}</p>{state.requestId!==undefined&&<small>Referencia: {state.requestId}</small>}</div>}{state.success!==undefined&&<div className="form-status form-success" role="status"><p>{state.success}</p></div>}</>}
function Input({state,name,label,type='text',...props}:{state:AuthFormState;name:string;label:string;type?:string;autoComplete?:string;minLength?:number;maxLength?:number;required?:boolean;placeholder?:string}){const invalid=state.fieldErrors[name]!==undefined;return <div className="auth-field"><label htmlFor={name}>{label}</label><input aria-describedby={invalid?`${name}-errors`:undefined} aria-invalid={invalid} id={name} name={name} type={type} {...props}/><Errors field={name} state={state}/></div>}
function Submit({pendingLabel,children}:{pendingLabel:string;children:string}){const{pending}=useFormStatus();return <button aria-disabled={pending} className="button primary auth-submit" disabled={pending} type="submit">{pending?pendingLabel:children}</button>}
export function LoginForm(){const[state,action]=useActionState(loginAction,initialAuthState);return <form action={action} className="auth-form"><Status state={state}/><Input autoComplete="email" label="Correo electrónico" maxLength={254} name="email" required state={state} type="email"/><Input autoComplete="current-password" label="Contraseña" maxLength={128} minLength={12} name="password" required state={state} type="password"/><div className="auth-form-row"><Link href={'/recuperar-password' as Route}>¿Has olvidado tu contraseña?</Link></div><Submit pendingLabel="Accediendo…">Entrar</Submit><p className="auth-switch">¿Aún no tienes cuenta? <Link href={'/registro' as Route}>Crear una cuenta</Link></p></form>}
export function RegisterForm(){const[state,action]=useActionState(registerAction,initialAuthState);return <form action={action} className="auth-form"><Status state={state}/><div className="auth-fields-pair"><Input autoComplete="given-name" label="Nombre" maxLength={100} name="nombre" required state={state}/><Input autoComplete="family-name" label="Apellidos" maxLength={100} name="apellidos" required state={state}/></div><Input autoComplete="email" label="Correo electrónico" maxLength={254} name="email" required state={state} type="email"/><Input autoComplete="new-password" label="Contraseña" maxLength={128} minLength={12} name="password" required state={state} type="password"/><p className="field-help">Mínimo 12 caracteres.</p><Input autoComplete="bday" label="Fecha de nacimiento" name="fecha_nacimiento" required state={state} type="date"/><label className="check-field"><input aria-describedby={state.fieldErrors.declaracion_mayoria_edad!==undefined?'declaracion_mayoria_edad-errors':undefined} aria-invalid={state.fieldErrors.declaracion_mayoria_edad!==undefined} name="declaracion_mayoria_edad" required type="checkbox"/><span>Confirmo que soy <Link href="/legal/mayoria-edad">mayor de edad</Link>.</span></label><Errors field="declaracion_mayoria_edad" state={state}/><label className="check-field"><input aria-describedby={state.fieldErrors.aceptacion_condiciones_alcohol!==undefined?'aceptacion_condiciones_alcohol-errors':undefined} aria-invalid={state.fieldErrors.aceptacion_condiciones_alcohol!==undefined} name="aceptacion_condiciones_alcohol" required type="checkbox"/><span>Acepto las <Link href="/legal/mayoria-edad">condiciones aplicables a la compra de alcohol</Link>.</span></label><Errors field="aceptacion_condiciones_alcohol" state={state}/><p className="field-help">Al crear una cuenta, aceptas los <Link href="/legal/terminos">Términos y Condiciones</Link> y la <Link href="/legal/privacidad">Política de Privacidad</Link>.</p><Submit pendingLabel="Creando cuenta…">Crear cuenta</Submit><p className="auth-switch">¿Ya tienes cuenta? <Link href="/acceso">Iniciar sesión</Link></p></form>}
export function RecoveryForm(){const[state,action]=useActionState(recoveryAction,initialAuthState);return state.success!==undefined?<div className="auth-form"><Status state={state}/><Link className="button secondary" href="/acceso">Volver al acceso</Link></div>:<form action={action} className="auth-form"><Status state={state}/><Input autoComplete="email" label="Correo electrónico" maxLength={254} name="email" required state={state} type="email"/><p className="field-help">Por seguridad, la respuesta será la misma exista o no la cuenta.</p><Submit pendingLabel="Enviando…">Enviar enlace</Submit><p className="auth-switch"><Link href="/acceso">Volver al acceso</Link></p></form>}
export function ResetForm({token}:{token:string}){const[state,action]=useActionState(resetAction,initialAuthState);return state.success!==undefined?<div className="auth-form"><Status state={state}/><Link className="button primary" href="/acceso">Iniciar sesión</Link></div>:<form action={action} className="auth-form"><Status state={state}/><input name="token" type="hidden" value={token}/><Errors field="token" state={state}/><Input autoComplete="new-password" label="Nueva contraseña" maxLength={128} minLength={12} name="password_nueva" required state={state} type="password"/><Input autoComplete="new-password" label="Confirmar contraseña" maxLength={128} minLength={12} name="confirmacion_password" required state={state} type="password"/><Submit pendingLabel="Actualizando…">Guardar contraseña</Submit></form>}
