import { randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import request from 'supertest';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { AppModule } from '../src/app.module.js';
import { configureApplication } from '../src/bootstrap.js';
import { SessionService } from '../src/common/security/session.service.js';
const HASH='scrypt$16384$8$1$00000000000000000000000000000000$00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000';
function required<T>(value:T|undefined):T{if(value===undefined)throw new Error('Fixture ausente.');return value;}
describe('APIs 037/038/025/026 — admin vinos E2E',()=>{let app:INestApplication;let pool:Pool;let token:string;let adminId:string;let bodegaId:string;
 beforeAll(async()=>{pool=new Pool({connectionString:process.env.DATABASE_URL});const moduleRef=await Test.createTestingModule({imports:[AppModule]}).compile();app=moduleRef.createNestApplication();configureApplication(app as Parameters<typeof configureApplication>[0]);await app.init();const admin=await pool.query<{id:string}>(`INSERT INTO usuario (email,password_hash,rol,estado) VALUES ($1,$2,'administrador','activo') RETURNING id`,[`admin-wine-${randomUUID()}@teralya.test`,HASH]);adminId=required(admin.rows[0]).id;const bodega=await pool.query<{id:string}>(`INSERT INTO bodega (nombre_comercial,razon_social,cif_vat,estado,tipo,comision,email_principal,telefono,persona_contacto) VALUES ('Admin Wine Bodega','Admin Wine SL',$1,'aprobada','estandar',10.00,$2,'+34910000000','Responsable') RETURNING id`,[`ESB${randomUUID().replaceAll('-','').slice(0,8)}`,`b-${randomUUID()}@teralya.test`]);bodegaId=required(bodega.rows[0]).id;token=(await app.get(SessionService).issue({usuarioId:adminId,rol:'administrador'})).accessToken;});afterAll(async()=>{await pool.end();await app.close();});const auth=()=>({Authorization:`Bearer ${token}`});
 async function wine(fit=true){const row=await pool.query<{id:string}>(`INSERT INTO vino (bodega_id,nombre_comercial,precio,moneda,stock_disponible,disponible_venta,estado) VALUES ($1,'Vino pendiente',12.00,'EUR',$2,$3,'pendiente_revision') RETURNING id`,[bodegaId,fit?10:0,fit]);const id=required(row.rows[0]).id;if(fit)await pool.query(`INSERT INTO imagen (tipo_entidad,entidad_id,nombre_archivo,url,formato,tamanio_bytes,es_principal,orden,alt_text,activa,subido_por) VALUES ('vino',$1,'wine.webp',$2,'webp',1000,true,0,'Botella',true,$3)`,[id,`https://cdn.test/${id}.webp`,adminId]);return id;}
 it('lista solo pendientes y ofrece detalle administrativo',async()=>{const id=await wine();const list=await request(app.getHttpServer() as Server).get('/admin/vinos?estado=pendiente_revision&page=1&page_size=100').set(auth()).expect(200);expect((list.body as {items:{id:string}[]}).items.some(item=>item.id===id)).toBe(true);const detail=await request(app.getHttpServer() as Server).get(`/admin/vinos/${id}`).set(auth()).expect(200);expect(detail.body).toMatchObject({id,estado:'pendiente_revision',bodega:{id:bodegaId,estado:'aprobada'}});});
 it('serializa publicación, audita y despublica estrictamente a oculto',async()=>{const id=await wine();const publish=()=>request(app.getHttpServer() as Server).post(`/admin/vinos/${id}/publicar`).set(auth());const responses=await Promise.all([publish(),publish()]);expect(responses.map(response=>response.status).sort()).toEqual([200,409]);const hidden=await request(app.getHttpServer() as Server).post(`/admin/vinos/${id}/despublicar`).set(auth()).expect(200);expect(hidden.body).toMatchObject({estado:'oculto'});await request(app.getHttpServer() as Server).post(`/admin/vinos/${id}/despublicar`).set(auth()).expect(409);const audit=await pool.query<{accion:string}>(`SELECT accion FROM auditoria WHERE entidad_id=$1 ORDER BY fecha_hora`,[id]);expect(audit.rows.map(row=>row.accion)).toEqual(['publicar_vino','despublicar_vino']);});
 it('rechaza publicación sin aptitud sin mutar el estado',async()=>{const id=await wine(false);await request(app.getHttpServer() as Server).post(`/admin/vinos/${id}/publicar`).set(auth()).expect(400);const state=await pool.query<{estado:string}>('SELECT estado FROM vino WHERE id=$1',[id]);expect(state.rows[0]?.estado).toBe('pendiente_revision');});
});
