import { BadRequestException,ConflictException,NotFoundException } from '@nestjs/common';
import { describe,expect,it,vi } from 'vitest';
import type { AdminVinosRepository,AdminWineRecord } from '../src/modules/admin/admin-vinos.repository.js';
import { AdminVinosService } from '../src/modules/admin/admin-vinos.service.js';
const ID='11111111-1111-4111-8111-111111111111';
const WINE={id:ID,bodega_id:'22222222-2222-4222-8222-222222222222',nombre_comercial:'Reserva',precio:'10.00',moneda:'EUR',disponible_venta:true,estado:'pendiente_revision',stock_disponible:10,stock_reservado:0,stock_minimo:0,created_at:'2026-07-14T10:00:00Z',updated_at:'2026-07-14T11:00:00Z',bodega_nombre:'Bodega',bodega_estado:'aprobada',bodega_created_at:'2026-01-01T00:00:00Z',imagenes:[],slug:null,sku:null,tipo_vino:null,anada:null,pais:null,region:null,denominacion_origen:null,variedades_uva:null,crianza:null,meses_crianza:null,graduacion_alcoholica:null,volumen_ml:null,descripcion_corta:null,descripcion_completa:null,nota_cata:null,maridaje:null,temperatura_servicio:null,certificaciones:null,premios:null,produccion_limitada:null,peso_gramos:null,plazo_preparacion_dias:null,botellas_por_caja:null,bodega_razon_social:null,bodega_cif_vat:null,bodega_pais_contacto:null} as AdminWineRecord;
function setup(){const repository={listar:vi.fn(),obtener:vi.fn(),publicar:vi.fn(),despublicar:vi.fn()};return{repository,service:new AdminVinosService(repository as unknown as AdminVinosRepository)};}
describe('APIs 037/038/025/026 admin vinos',()=>{
 it('pagina pendientes y proyecta bodega administrativa',async()=>{const{repository,service}=setup();repository.listar.mockResolvedValue({items:[WINE],total:21});await expect(service.listar(2,20)).resolves.toMatchObject({page:2,total_items:21,total_pages:2,items:[{id:ID,bodega:{estado:'aprobada'}}]});});
 it('devuelve detalle y oculta nulos',async()=>{const{repository,service}=setup();repository.obtener.mockResolvedValue(WINE);const result=await service.obtener(ID);expect(result).toMatchObject({id:ID,imagenes:[],stock_reservado:0});expect(result).not.toHaveProperty('slug');});
 it('mapea transición publicada y oculta',async()=>{const{repository,service}=setup();repository.publicar.mockResolvedValue({kind:'updated',wine:{...WINE,estado:'publicado'}});repository.despublicar.mockResolvedValue({kind:'updated',wine:{...WINE,estado:'oculto'}});await expect(service.publicar(ID,'admin')).resolves.toMatchObject({estado:'publicado'});await expect(service.despublicar(ID,'admin')).resolves.toMatchObject({estado:'oculto'});});
 it('traduce estado inválido, aptitud e inexistencia',async()=>{const{repository,service}=setup();repository.publicar.mockResolvedValueOnce({kind:'conflict'}).mockResolvedValueOnce({kind:'invalid'}).mockResolvedValueOnce({kind:'missing'});await expect(service.publicar(ID,'admin')).rejects.toBeInstanceOf(ConflictException);await expect(service.publicar(ID,'admin')).rejects.toBeInstanceOf(BadRequestException);await expect(service.publicar(ID,'admin')).rejects.toBeInstanceOf(NotFoundException);});
});
