import { randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import request from 'supertest';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { AppModule } from '../src/app.module.js';
import { configureApplication } from '../src/bootstrap.js';
const HASH='scrypt$16384$8$1$00000000000000000000000000000000$00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000';
function required<T>(value:T|undefined):T{if(value===undefined)throw new Error('Fixture ausente.');return value;}
describe('API-009/010 catálogo público E2E',()=>{let app:INestApplication;let pool:Pool;let visibleId:string;let unavailableId:string;let draftId:string;
 beforeAll(async()=>{pool=new Pool({connectionString:process.env.DATABASE_URL});const moduleRef=await Test.createTestingModule({imports:[AppModule]}).compile();app=moduleRef.createNestApplication();configureApplication(app as Parameters<typeof configureApplication>[0]);await app.init();const b=await pool.query<{id:string}>(`INSERT INTO bodega (nombre_comercial,razon_social,cif_vat,estado,tipo,comision,email_principal,telefono,persona_contacto) VALUES ('Bodega Buscable','Bodega Buscable SL',$1,'aprobada','estandar',10.00,$2,'+34910000000','Responsable') RETURNING id`,[`ESB${randomUUID().replaceAll('-','').slice(0,8)}`,`catalog-${randomUUID()}@teralya.test`]);const bodegaId=required(b.rows[0]).id;const uploader=await pool.query<{id:string}>(`INSERT INTO usuario (email,password_hash,rol,estado,bodega_id) VALUES ($1,$2,'bodega','activo',$3) RETURNING id`,[`catalog-u-${randomUUID()}@teralya.test`,HASH,bodegaId]);const uploaderId=required(uploader.rows[0]).id;const insert=async(name:string,state:string,stock:number,available:boolean,date:string|null)=>{const row=await pool.query<{id:string}>(`INSERT INTO vino (bodega_id,nombre_comercial,tipo_vino,region,denominacion_origen,precio,moneda,stock_disponible,disponible_venta,estado,fecha_publicacion) VALUES ($1,$2,'tinto','Rioja','DOCa Rioja',15.00,'EUR',$3,$4,$5,$6) RETURNING id`,[bodegaId,name,stock,available,state,date]);return required(row.rows[0]).id;};visibleId=await insert('Reserva Visible','publicado',10,true,'2026-07-14T10:00:00Z');unavailableId=await insert('Reserva Agotada','publicado',0,false,'2026-07-14T11:00:00Z');draftId=await insert('Reserva Privada','borrador',10,true,null);await pool.query(`INSERT INTO imagen (tipo_entidad,entidad_id,nombre_archivo,url,formato,tamanio_bytes,es_principal,orden,alt_text,activa,subido_por) VALUES ('vino',$1,'active.webp',$2,'webp',1000,true,0,'Botella activa',true,$3),('vino',$1,'inactive.webp',$4,'webp',1000,false,1,'Botella inactiva',false,$3)`,[unavailableId,`https://cdn.test/${unavailableId}-a.webp`,uploaderId,`https://cdn.test/${unavailableId}-i.webp`]);});afterAll(async()=>{await pool.end();await app.close();});
 it('lista solo vendibles y filtra por vino/bodega y atributos sin caché',async()=>{const response=await request(app.getHttpServer() as Server).get('/vinos?q=buscable&tipo_vino=tinto&region=Rioja&denominacion_origen=DOCa%20Rioja&precio_min=10.00&precio_max=20.00').expect(200);expect(response.headers['cache-control']).toBe('no-store');const ids=(response.body as {items:{id:string}[]}).items.map(item=>item.id);expect(ids).toContain(visibleId);expect(ids).not.toContain(unavailableId);expect(ids).not.toContain(draftId);});
 it('rechaza precio invertido',async()=>{const response=await request(app.getHttpServer() as Server).get('/vinos?precio_min=20.00&precio_max=10.00').expect(400);expect(response.body).toMatchObject({code:'VALIDATION_ERROR'});});
 it('detalle mantiene publicado agotado, solo imágenes activas, y oculta borrador',async()=>{const detail=await request(app.getHttpServer() as Server).get(`/vinos/${unavailableId}`).expect(200);expect(detail.headers['cache-control']).toBe('no-store');expect(detail.body).toMatchObject({id:unavailableId,disponible_venta:false,imagenes:[{alt_text:'Botella activa'}]});expect((detail.body as {imagenes:unknown[]}).imagenes).toHaveLength(1);expect(detail.body).not.toHaveProperty('stock_disponible');expect(detail.body).not.toHaveProperty('estado');await request(app.getHttpServer() as Server).get(`/vinos/${draftId}`).expect(404);});
});
