import { BadRequestException,NotFoundException } from '@nestjs/common';
import { describe,expect,it,vi } from 'vitest';
import type { CatalogRepository,CatalogWineRecord } from '../src/modules/vinos/catalog.repository.js';
import { CatalogService } from '../src/modules/vinos/catalog.service.js';
const ID='11111111-1111-4111-8111-111111111111';
const WINE={id:ID,bodega_id:'22222222-2222-4222-8222-222222222222',nombre_comercial:'Reserva',precio:'10.00',moneda:'EUR',disponible_venta:false,bodega_nombre:'Bodega',imagenes:[],slug:null,tipo_vino:null,anada:null,pais:null,region:null,denominacion_origen:null,variedades_uva:null,crianza:null,meses_crianza:null,graduacion_alcoholica:null,volumen_ml:null,descripcion_corta:null,descripcion_completa:null,nota_cata:null,maridaje:null,temperatura_servicio:null,certificaciones:null,premios:null,produccion_limitada:null,bodega_slug:null,bodega_logo_url:null,bodega_region:null,bodega_pais:null,bodega_denominacion_origen:null} as CatalogWineRecord;
function setup(){const repository={listar:vi.fn(),obtener:vi.fn()};return{repository,service:new CatalogService(repository as unknown as CatalogRepository)};}
describe('API-009/010 catálogo público',()=>{
 it('pagina el resultado filtrado sin exponer campos internos',async()=>{const{repository,service}=setup();repository.listar.mockResolvedValue({items:[WINE],total:21});const result=await service.listar({page:2,page_size:20});expect(result).toMatchObject({page:2,total_items:21,total_pages:2,items:[{id:ID,bodega:{nombre_comercial:'Bodega'}}]});expect(result.items[0]).not.toHaveProperty('stock_disponible');expect(result.items[0]).not.toHaveProperty('estado');});
 it('rechaza rango de precios invertido antes de consultar',async()=>{const{repository,service}=setup();await expect(service.listar({precio_min:'20.00',precio_max:'10.00',page:1,page_size:20})).rejects.toBeInstanceOf(BadRequestException);expect(repository.listar).not.toHaveBeenCalled();});
 it('permite detalle publicado no disponible y devuelve imágenes activas proyectadas',async()=>{const{repository,service}=setup();repository.obtener.mockResolvedValue({...WINE,imagenes:[{id:'33333333-3333-4333-8333-333333333333',url:'https://cdn.test/w.webp',es_principal:true,orden:0,alt_text:'Botella',resolucion:null}]});const result=await service.obtener(ID);expect(result).toMatchObject({id:ID,disponible_venta:false,imagenes:[{es_principal:true}]});expect(result).not.toHaveProperty('stock_disponible');});
 it('oculta UUID inválido y vino no público con 404',async()=>{const{repository,service}=setup();await expect(service.obtener('bad')).rejects.toBeInstanceOf(NotFoundException);repository.obtener.mockResolvedValue(null);await expect(service.obtener(ID)).rejects.toBeInstanceOf(NotFoundException);});
});
