import { BadRequestException, ConflictException, NotFoundException } from '@nestjs/common';
import { describe, expect, it, vi } from 'vitest';
import type { SessionActor } from '../src/common/security/session.service.js';
import type { DatabaseService } from '../src/common/database/database.service.js';
import { DireccionesRepository, type AddressRecord } from '../src/modules/direcciones/direcciones.repository.js';
import { DireccionesService } from '../src/modules/direcciones/direcciones.service.js';

const ID='11111111-1111-4111-8111-111111111111';
const ACTOR:SessionActor={usuarioId:'22222222-2222-4222-8222-222222222222',rol:'comprador',issuedAt:new Date(),expiresAt:new Date(Date.now()+1000)};
const INPUT={uso:'envio' as const,nombre_destinatario:'Ana',direccion:'Calle 1',codigo_postal:'28001',ciudad:'Madrid',pais:'España'};
const RECORD:AddressRecord={id:ID,propietario_tipo:'comprador',propietario_id:ACTOR.usuarioId,nombre_identificativo:null,destinatario:'Ana',empresa:null,direccion:'Calle 1',direccion_adicional:null,codigo_postal:'28001',ciudad:'Madrid',provincia:null,pais:'España',persona_contacto:null,telefono:null,email:null,es_envio:true,es_facturacion:false,es_principal:false,activa:true,created_at:'2026-01-01T00:00:00Z',updated_at:'2026-01-01T00:00:00Z'};

describe('API-043–046 — direcciones propias',()=>{
  it('deriva propietario comprador y normaliza la respuesta',async()=>{const repository={crear:vi.fn().mockResolvedValue({kind:'created',address:RECORD})};const service=new DireccionesService(repository as unknown as DireccionesRepository);await expect(service.crear(ACTOR,ID,INPUT)).resolves.toMatchObject({replayed:false,address:{uso:'envio',nombre_destinatario:'Ana'}});expect(repository.crear).toHaveBeenCalledWith({tipo:'comprador',id:ACTOR.usuarioId,usuarioId:ACTOR.usuarioId},ID,INPUT,expect.objectContaining({es_principal:false}));});
  it('deriva propietario bodega del bodega_id y conserva usuario para auditoría',async()=>{const repository={listar:vi.fn().mockResolvedValue([])};const service=new DireccionesService(repository as unknown as DireccionesRepository);await service.listar({...ACTOR,rol:'bodega',bodegaId:'33333333-3333-4333-8333-333333333333'});expect(repository.listar).toHaveBeenCalledWith({tipo:'bodega',id:'33333333-3333-4333-8333-333333333333',usuarioId:ACTOR.usuarioId},undefined);});
  it('interpreta el filtro como capacidad e incluye ambos',async()=>{const query=vi.fn().mockResolvedValue([]);const repository=new DireccionesRepository({query} as unknown as DatabaseService);const owner={tipo:'comprador' as const,id:ACTOR.usuarioId,usuarioId:ACTOR.usuarioId};await repository.listar(owner,'envio');expect(query.mock.calls[0]?.[0]).toContain('AND es_envio=true');expect(query.mock.calls[0]?.[0]).not.toContain('es_facturacion=false');await repository.listar(owner,'facturacion');expect(query.mock.calls[1]?.[0]).toContain('AND es_facturacion=true');});
  it('devuelve el snapshot durable en un replay idéntico',async()=>{const response={id:ID,uso:'envio' as const,nombre_destinatario:'Ana',direccion:'Calle 1',codigo_postal:'28001',ciudad:'Madrid',pais:'España',es_principal:false,activa:true,created_at:'2026-01-01T00:00:00.000Z',updated_at:'2026-01-01T00:00:00.000Z'};const service=new DireccionesService({crear:vi.fn().mockResolvedValue({kind:'replayed',response})} as unknown as DireccionesRepository);await expect(service.crear(ACTOR,ID,INPUT)).resolves.toEqual({address:response,replayed:true});});
  it('rechaza UUID inválido y reutilización conflictiva',async()=>{const repository={crear:vi.fn().mockResolvedValue({kind:'conflict'})};const service=new DireccionesService(repository as unknown as DireccionesRepository);await expect(service.crear(ACTOR,'bad',INPUT)).rejects.toBeInstanceOf(BadRequestException);await expect(service.crear(ACTOR,ID,INPUT)).rejects.toBeInstanceOf(ConflictException);});
  it('oculta una dirección ajena o inexistente como 404',async()=>{const service=new DireccionesService({actualizar:vi.fn().mockResolvedValue(null)} as unknown as DireccionesRepository);await expect(service.actualizar(ACTOR,ID,{ciudad:'Bilbao'})).rejects.toBeInstanceOf(NotFoundException);});
  it('rechaza PATCH vacío y colisión de principal',async()=>{const repository={actualizar:vi.fn().mockResolvedValue('principal_conflict')};const service=new DireccionesService(repository as unknown as DireccionesRepository);await expect(service.actualizar(ACTOR,ID,{})).rejects.toBeInstanceOf(BadRequestException);await expect(service.actualizar(ACTOR,ID,{es_principal:true})).rejects.toBeInstanceOf(ConflictException);});
});
