import { BadRequestException,ConflictException,GoneException,NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { describe,expect,it,vi } from 'vitest';
import type { SessionActor } from '../src/common/security/session.service.js';
import { ConfirmationTokenService } from '../src/modules/imagenes/confirmation-token.service.js';
import type { ImagenesRepository,ImageRecord } from '../src/modules/imagenes/imagenes.repository.js';
import { ImagenesService } from '../src/modules/imagenes/imagenes.service.js';
const VINO='11111111-1111-4111-8111-111111111111',BODEGA='22222222-2222-4222-8222-222222222222',UPLOAD='33333333-3333-4333-8333-333333333333';
const ACTOR:SessionActor={usuarioId:'44444444-4444-4444-8444-444444444444',rol:'bodega',bodegaId:BODEGA,issuedAt:new Date(),expiresAt:new Date(Date.now()+10000)};
const CONFIG=new ConfigService({IMAGE_CONFIRMATION_HMAC_SECRET:'a'.repeat(32),OBJECT_STORAGE_CDN_BASE_URL:'https://cdn.test'});
const IMAGE:ImageRecord={id:UPLOAD,url:'https://cdn.test/key',es_principal:false,orden:0,alt_text:'Botella',formato:'jpeg',activa:true,fecha_subida:new Date(),updated_at:new Date(),nombre_archivo:'wine.jpg',tamanio_bytes:10,resolucion:null};
function setup(){const repository={bodegaPuedeOperar:vi.fn().mockResolvedValue(true),ownership:vi.fn().mockResolvedValue('owned'),confirmar:vi.fn(),actualizar:vi.fn(),desactivar:vi.fn()};const storage={presignPut:vi.fn().mockResolvedValue('https://upload.test/signed'),head:vi.fn()};const tokens=new ConfirmationTokenService(CONFIG);return{repository,storage,tokens,service:new ImagenesService(repository as unknown as ImagenesRepository,tokens,storage,CONFIG)};}
const upload={upload_id:UPLOAD,nombre_archivo:'wine.jpg',content_type:'image/jpeg' as const,tamanio_bytes:10,checksum_sha256:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='};
describe('APIs 047-050 imágenes',()=>{
 it('prefirma con cabeceras obligatorias y token HMAC ligado a propietario/vino',async()=>{const{service,storage,tokens}=setup();const result=await service.autorizar(ACTOR,VINO,upload);expect(storage.presignPut).toHaveBeenCalledWith(expect.objectContaining({contentType:'image/jpeg',contentLength:10,expiresInSeconds:600}));expect(result.required_headers).toEqual({'Content-Type':'image/jpeg','x-amz-checksum-sha256':upload.checksum_sha256,'If-None-Match':'*'});expect(tokens.verify(result.confirmation_token)).toMatchObject({uploadId:UPLOAD,vinoId:VINO,bodegaId:BODEGA});});
 it('rechaza token manipulado, caducado y objeto HEAD discordante',async()=>{const{service,storage,tokens}=setup();await expect(service.confirmar(ACTOR,VINO,{upload_id:UPLOAD,confirmation_token:'x'.repeat(32),alt_text:'Botella'})).rejects.toBeInstanceOf(BadRequestException);const expired=tokens.issue({v:1,uploadId:UPLOAD,key:'k',vinoId:VINO,bodegaId:BODEGA,usuarioId:ACTOR.usuarioId,nombreArchivo:'x.jpg',contentType:'image/jpeg',size:10,checksum:upload.checksum_sha256,exp:1});await expect(service.confirmar(ACTOR,VINO,{upload_id:UPLOAD,confirmation_token:expired,alt_text:'Botella'})).rejects.toBeInstanceOf(GoneException);const valid=tokens.issue({v:1,uploadId:UPLOAD,key:'k',vinoId:VINO,bodegaId:BODEGA,usuarioId:ACTOR.usuarioId,nombreArchivo:'x.jpg',contentType:'image/jpeg',size:10,checksum:upload.checksum_sha256,exp:Math.floor(Date.now()/1000)+100});storage.head.mockResolvedValue({contentType:'image/png',contentLength:10,checksumSha256:upload.checksum_sha256});await expect(service.confirmar(ACTOR,VINO,{upload_id:UPLOAD,confirmation_token:valid,alt_text:'Botella'})).rejects.toBeInstanceOf(BadRequestException);});
 it('confirma tras HEAD exacto y conserva replay 200 lógico',async()=>{const{service,storage,tokens,repository}=setup();const token=tokens.issue({v:1,uploadId:UPLOAD,key:'k',vinoId:VINO,bodegaId:BODEGA,usuarioId:ACTOR.usuarioId,nombreArchivo:'x.jpg',contentType:'image/jpeg',size:10,checksum:upload.checksum_sha256,exp:Math.floor(Date.now()/1000)+100});storage.head.mockResolvedValue({contentType:'image/jpeg',contentLength:10,checksumSha256:upload.checksum_sha256});repository.confirmar.mockResolvedValueOnce({kind:'created',image:IMAGE}).mockResolvedValueOnce({kind:'replayed',response:{id:UPLOAD}});await expect(service.confirmar(ACTOR,VINO,{upload_id:UPLOAD,confirmation_token:token,alt_text:'Botella'})).resolves.toMatchObject({replayed:false});await expect(service.confirmar(ACTOR,VINO,{upload_id:UPLOAD,confirmation_token:token,alt_text:'Botella'})).resolves.toMatchObject({replayed:true});});
 it('traduce reutilización distinta y última imagen protegida a 409',async()=>{const{service,storage,tokens,repository}=setup();const token=tokens.issue({v:1,uploadId:UPLOAD,key:'k',vinoId:VINO,bodegaId:BODEGA,usuarioId:ACTOR.usuarioId,nombreArchivo:'x.jpg',contentType:'image/jpeg',size:10,checksum:upload.checksum_sha256,exp:Math.floor(Date.now()/1000)+100});storage.head.mockResolvedValue({contentType:'image/jpeg',contentLength:10,checksumSha256:upload.checksum_sha256});repository.confirmar.mockResolvedValue({kind:'conflict'});await expect(service.confirmar(ACTOR,VINO,{upload_id:UPLOAD,confirmation_token:token,alt_text:'Otra'})).rejects.toBeInstanceOf(ConflictException);repository.desactivar.mockResolvedValue('conflict');await expect(service.desactivar(ACTOR,VINO,UPLOAD)).rejects.toBeInstanceOf(ConflictException);});
 it('oculta recursos de otra bodega antes de tocar storage',async()=>{const{service,repository,storage}=setup();repository.ownership.mockResolvedValue('foreign');await expect(service.autorizar(ACTOR,VINO,upload)).rejects.toBeInstanceOf(NotFoundException);expect(storage.presignPut).not.toHaveBeenCalled();});
});
