import { randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import request from 'supertest';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { AppModule } from '../src/app.module.js';
import { configureApplication } from '../src/bootstrap.js';
import { SessionService } from '../src/common/security/session.service.js';
import { OBJECT_STORAGE,type ObjectStorageService,type PresignPutInput,type StoredObjectMetadata } from '../src/modules/imagenes/object-storage.service.js';
const HASH='scrypt$16384$8$1$00000000000000000000000000000000$00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000';
const CHECKSUM='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';
class FakeStorage implements ObjectStorageService{readonly objects=new Map<string,StoredObjectMetadata>();presignPut(input:PresignPutInput):Promise<string>{this.objects.set(input.key,{contentType:input.contentType,contentLength:input.contentLength,checksumSha256:input.checksumSha256});return Promise.resolve(`https://upload.test/${input.key}`);}head(key:string):Promise<StoredObjectMetadata|null>{return Promise.resolve(this.objects.get(key)??null);}}
function required<T>(value:T|undefined):T{if(value===undefined)throw new Error('Fixture ausente.');return value;}
describe('APIs 047-050 imágenes — integración con storage falso',()=>{let app:INestApplication;let pool:Pool;let vinoId:string;let token:string;const storage=new FakeStorage();
 beforeAll(async()=>{pool=new Pool({connectionString:process.env.DATABASE_URL});const moduleRef=await Test.createTestingModule({imports:[AppModule]}).overrideProvider(OBJECT_STORAGE).useValue(storage).compile();app=moduleRef.createNestApplication();configureApplication(app as Parameters<typeof configureApplication>[0]);await app.init();const b=await pool.query<{id:string}>(`INSERT INTO bodega (nombre_comercial,razon_social,cif_vat,estado,tipo,comision,email_principal,telefono,persona_contacto) VALUES ('Bodega imágenes','Bodega imágenes SL',$1,'aprobada','estandar',10.00,$2,'+34910000000','Responsable') RETURNING id`,[`ESB${randomUUID().replaceAll('-','').slice(0,8)}`,`img-${randomUUID()}@teralya.test`]);const bodegaId=required(b.rows[0]).id;const u=await pool.query<{id:string}>(`INSERT INTO usuario (email,password_hash,rol,estado,bodega_id) VALUES ($1,$2,'bodega','activo',$3) RETURNING id`,[`img-u-${randomUUID()}@teralya.test`,HASH,bodegaId]);const userId=required(u.rows[0]).id;const v=await pool.query<{id:string}>(`INSERT INTO vino (bodega_id,nombre_comercial,precio,moneda,stock_disponible,disponible_venta,estado) VALUES ($1,'Vino imágenes',15.00,'EUR',10,true,'borrador') RETURNING id`,[bodegaId]);vinoId=required(v.rows[0]).id;token=(await app.get(SessionService).issue({usuarioId:userId,rol:'bodega',bodegaId})).accessToken;});
 afterAll(async()=>{await pool.end();await app.close();});const auth=()=>({Authorization:`Bearer ${token}`});
 async function authorize(uploadId:string){return request(app.getHttpServer() as Server).post(`/bodegas/yo/vinos/${vinoId}/imagenes/upload-url`).set(auth()).send({upload_id:uploadId,nombre_archivo:'botella.jpg',content_type:'image/jpeg',tamanio_bytes:1000,checksum_sha256:CHECKSUM}).expect(200);}
 function confirm(uploadId:string,confirmationToken:string,principal=false){return request(app.getHttpServer() as Server).post(`/bodegas/yo/vinos/${vinoId}/imagenes`).set(auth()).send({upload_id:uploadId,confirmation_token:confirmationToken,alt_text:'Botella de vino',es_principal:principal});}
 it('autoriza, confirma 201 y reproduce idénticamente con 200',async()=>{const id=randomUUID();const authorization=await authorize(id);expect(authorization.body).toMatchObject({upload_id:id,method:'PUT',required_headers:{'If-None-Match':'*'}});const confirmationToken=(authorization.body as {confirmation_token:string}).confirmation_token;const first=await confirm(id,confirmationToken,true).expect(201);expect(first.body).toMatchObject({id,es_principal:true,activa:true,formato:'jpeg'});const replay=await confirm(id,confirmationToken,true).expect(200);expect(replay.body).toEqual(first.body);await request(app.getHttpServer() as Server).delete(`/bodegas/yo/vinos/${vinoId}/imagenes/${id}`).set(auth()).expect(204);});
 it('actualiza principal de forma exclusiva y permite cero imágenes en borrador',async()=>{const a=randomUUID(),b=randomUUID();const aa=await authorize(a),bb=await authorize(b);await confirm(a,(aa.body as {confirmation_token:string}).confirmation_token,true).expect(201);await confirm(b,(bb.body as {confirmation_token:string}).confirmation_token,false).expect(201);await request(app.getHttpServer() as Server).patch(`/bodegas/yo/vinos/${vinoId}/imagenes/${b}`).set(auth()).send({es_principal:true,orden:2}).expect(200);const principals=await pool.query<{id:string}>('SELECT id FROM imagen WHERE entidad_id=$1 AND activa=true AND es_principal=true',[vinoId]);expect(principals.rows).toEqual([{id:b}]);await request(app.getHttpServer() as Server).delete(`/bodegas/yo/vinos/${vinoId}/imagenes/${a}`).set(auth()).expect(204);await request(app.getHttpServer() as Server).delete(`/bodegas/yo/vinos/${vinoId}/imagenes/${b}`).set(auth()).expect(204);});
 it('protege la última imagen solo en pendiente_revision/publicado y mantiene DELETE idempotente',async()=>{const id=randomUUID();const authz=await authorize(id);await confirm(id,(authz.body as {confirmation_token:string}).confirmation_token).expect(201);await pool.query("UPDATE vino SET estado='pendiente_revision' WHERE id=$1",[vinoId]);await request(app.getHttpServer() as Server).delete(`/bodegas/yo/vinos/${vinoId}/imagenes/${id}`).set(auth()).expect(409);await pool.query("UPDATE vino SET estado='borrador' WHERE id=$1",[vinoId]);await request(app.getHttpServer() as Server).delete(`/bodegas/yo/vinos/${vinoId}/imagenes/${id}`).set(auth()).expect(204);await request(app.getHttpServer() as Server).delete(`/bodegas/yo/vinos/${vinoId}/imagenes/${id}`).set(auth()).expect(204);});
});
