import { createHmac, randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { AppModule } from '../src/app.module.js';
import { configureApplication } from '../src/bootstrap.js';

const SECRET=process.env.STRIPE_WEBHOOK_SECRET??'whsec_ci_placeholder_0000000000',HASH='scrypt$16384$8$1$00000000000000000000000000000000$00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000';
function required<T>(value:T|undefined):T{if(value===undefined)throw new Error('Fixture ausente.');return value;}
describe('API-029 Stripe webhook E2E',()=>{let app:INestApplication,pool:Pool,order:string,payment:string,cart:string,wine1:string,wine2:string;
  // La línea prepara dos fixtures mediante asignación secuencial compacta.
  // eslint-disable-next-line @typescript-eslint/no-unused-expressions
  beforeAll(async()=>{pool=new Pool({connectionString:process.env.DATABASE_URL});const moduleRef=await Test.createTestingModule({imports:[AppModule]}).compile();app=moduleRef.createNestApplication({rawBody:true});configureApplication(app as Parameters<typeof configureApplication>[0]);await app.init();const buyer=required((await pool.query<{id:string}>(`INSERT INTO usuario(email,password_hash,rol,estado) VALUES($1,$2,'comprador','activo') RETURNING id`,[`hook-${randomUUID()}@test`,HASH])).rows[0]).id;await pool.query(`INSERT INTO comprador(usuario_id,fecha_nacimiento,declaracion_mayoria_edad,aceptacion_condiciones_alcohol) VALUES($1,'1990-01-01',true,true)`,[buyer]);const address=required((await pool.query<{id:string}>(`INSERT INTO direccion(propietario_tipo,propietario_id,destinatario,direccion,codigo_postal,ciudad,pais,es_envio,es_facturacion) VALUES('comprador',$1,'Buyer','Calle 1','28001','Madrid','ES',true,true) RETURNING id`,[buyer])).rows[0]).id;const bodega=async(name:string,commission:number)=>required((await pool.query<{id:string}>(`INSERT INTO bodega(nombre_comercial,estado,tipo,comision) VALUES($1,'aprobada','estandar',$2) RETURNING id`,[name,commission])).rows[0]).id;const b1=await bodega('Webhook A',10),b2=await bodega('Webhook B',20);const wine=async(owner:string,name:string)=>required((await pool.query<{id:string}>(`INSERT INTO vino(bodega_id,nombre_comercial,precio,moneda,stock_disponible,disponible_venta,estado) VALUES($1,$2,10,'EUR',5,true,'publicado') RETURNING id`,[owner,name])).rows[0]).id;wine1=await wine(b1,'A'),wine2=await wine(b2,'B');cart=required((await pool.query<{id:string}>(`INSERT INTO carrito(comprador_id,num_productos,num_botellas,subtotal,gastos_envio,descuentos,total) VALUES($1,2,3,30,3,1,32) RETURNING id`,[buyer])).rows[0]).id;await pool.query(`INSERT INTO carrito_item(carrito_id,vino_id,cantidad,precio_unitario,importe_total) VALUES($1,$2,2,10,20),($1,$3,1,10,10)`,[cart,wine1,wine2]);order=required((await pool.query<{id:string}>(`INSERT INTO pedido(numero_pedido,comprador_id,carrito_id,subtotal,gastos_envio,impuestos,descuentos,total,direccion_envio_id,direccion_envio_snapshot,direccion_facturacion_id,direccion_facturacion_snapshot,estado) VALUES($1,$2,$3,30,3,0,1,32,$4,'{}',$4,'{}','pendiente_pago') RETURNING id`,[`TER-${randomUUID()}`,buyer,cart,address])).rows[0]).id;payment=required((await pool.query<{id:string}>(`INSERT INTO pago(pedido_id,subtotal,gastos_envio,impuestos,comision_marketplace,total_cobrado,total_repartido,total_reembolsado,moneda,estado,stripe_checkout_session_id,stripe_checkout_expires_at) VALUES($1,30,3,0,0,32,0,0,'EUR','pendiente','cs_current',now()+interval '30 min') RETURNING id`,[order])).rows[0]).id;});afterAll(async()=>{await pool.end();await app.close();});
  function event(id:string,session='cs_old'){const amount='3200',metadata_signature=createHmac('sha256',SECRET).update([order,payment,'eur',amount].join('|')).digest('hex');const body=JSON.stringify({id,type:'checkout.session.completed',livemode:false,data:{object:{id:session,payment_status:'paid',amount_total:3200,currency:'eur',metadata:{pedido_id:order,pago_id:payment,currency:'eur',amount_cents:amount,metadata_signature}}}});const timestamp=Math.floor(Date.now()/1000),signature=createHmac('sha256',SECRET).update(`${String(timestamp)}.${body}`).digest('hex');return{body,header:`t=${String(timestamp)},v1=${signature}`};}
  function signed(id:string,type:string,session:string,orderId:string,paymentId:string,amountCents:number,status:'paid'|'unpaid'){const amount=String(amountCents),metadata_signature=createHmac('sha256',SECRET).update([orderId,paymentId,'eur',amount].join('|')).digest('hex');const body=JSON.stringify({id,type,livemode:false,data:{object:{id:session,payment_status:status,amount_total:amountCents,currency:'eur',metadata:{pedido_id:orderId,pago_id:paymentId,currency:'eur',amount_cents:amount,metadata_signature}}}});const timestamp=Math.floor(Date.now()/1000),signature=createHmac('sha256',SECRET).update(`${String(timestamp)}.${body}`).digest('hex');return{body,header:`t=${String(timestamp)},v1=${signature}`};}
  const send=(value:{body:string;header:string})=>request(app.getHttpServer() as Server).post('/sistema/webhooks/stripe').set('Content-Type','application/json').set('Stripe-Signature',value.header).send(value.body);
  it('acepta sesión antigua válida y procesa concurrentemente una sola vez',async()=>{const value=event('evt_concurrent');const responses=await Promise.all([send(value),send(value)]);expect(responses.map(response=>response.status).sort()).toEqual([200,200]);expect(responses.map(response=>(response.body as {status:string}).status).sort()).toEqual(['duplicate','processed']);const [items,subs,stocks,pay,car]=await Promise.all([pool.query<{total:number}>('SELECT count(*)::int total FROM pedido_item WHERE pedido_id=$1',[order]),pool.query<{total:number}>('SELECT count(*)::int total FROM subpedido WHERE pedido_id=$1',[order]),pool.query<{id:string;stock_disponible:number}>('SELECT id,stock_disponible FROM vino WHERE id=ANY($1::uuid[]) ORDER BY id',[[wine1,wine2]]),pool.query<{comision_marketplace:string;total_repartido:string;referencia_stripe:string}>('SELECT comision_marketplace::text,total_repartido::text,referencia_stripe FROM pago WHERE id=$1',[payment]),pool.query<{estado:string}>('SELECT estado FROM carrito WHERE id=$1',[cart])]);expect(required(items.rows[0]).total).toBe(2);expect(required(subs.rows[0]).total).toBe(2);expect(stocks.rows.map(row=>row.stock_disponible).sort()).toEqual([3,4]);expect(required(pay.rows[0])).toEqual({comision_marketplace:'4.00',total_repartido:'0.00',referencia_stripe:'cs_old'});expect(required(car.rows[0]).estado).toBe('convertido');});
  it('replay con otro event id no duplica líneas ni stock',async()=>{await send(event('evt_second_success')).expect(200);expect(required((await pool.query<{total:number}>('SELECT count(*)::int total FROM pedido_item WHERE pedido_id=$1',[order])).rows[0]).total).toBe(2);expect(required((await pool.query<{stock_disponible:number}>('SELECT stock_disponible FROM vino WHERE id=$1',[wine1])).rows[0]).stock_disponible).toBe(3);});
  it('evita oversell con rollback reintentable y aplica solo negativos de la sesión actual',async()=>{const buyer=required((await pool.query<{id:string}>(`INSERT INTO usuario(email,password_hash,rol,estado) VALUES($1,$2,'comprador','activo') RETURNING id`,[`stock-${randomUUID()}@test`,HASH])).rows[0]).id;await pool.query(`INSERT INTO comprador(usuario_id,fecha_nacimiento,declaracion_mayoria_edad,aceptacion_condiciones_alcohol) VALUES($1,'1990-01-01',true,true)`,[buyer]);const address=required((await pool.query<{id:string}>(`INSERT INTO direccion(propietario_tipo,propietario_id,destinatario,direccion,codigo_postal,ciudad,pais,es_envio,es_facturacion) VALUES('comprador',$1,'Buyer','Calle 2','28002','Madrid','ES',true,true) RETURNING id`,[buyer])).rows[0]).id;const newCart=required((await pool.query<{id:string}>(`INSERT INTO carrito(comprador_id,num_productos,num_botellas,subtotal,gastos_envio,descuentos,total) VALUES($1,1,4,40,0,0,40) RETURNING id`,[buyer])).rows[0]).id;await pool.query(`INSERT INTO carrito_item(carrito_id,vino_id,cantidad,precio_unitario,importe_total) VALUES($1,$2,4,10,40)`,[newCart,wine1]);const newOrder=required((await pool.query<{id:string}>(`INSERT INTO pedido(numero_pedido,comprador_id,carrito_id,subtotal,gastos_envio,impuestos,descuentos,total,direccion_envio_id,direccion_envio_snapshot,direccion_facturacion_id,direccion_facturacion_snapshot,estado) VALUES($1,$2,$3,40,0,0,0,40,$4,'{}',$4,'{}','pendiente_pago') RETURNING id`,[`TER-${randomUUID()}`,buyer,newCart,address])).rows[0]).id;const newPayment=required((await pool.query<{id:string}>(`INSERT INTO pago(pedido_id,subtotal,gastos_envio,impuestos,comision_marketplace,total_cobrado,total_repartido,total_reembolsado,moneda,estado,stripe_checkout_session_id,stripe_checkout_expires_at) VALUES($1,40,0,0,0,40,0,0,'EUR','pendiente','cs_stock_current',now()+interval '30 min') RETURNING id`,[newOrder])).rows[0]).id;await send(signed('evt_stock','checkout.session.completed','cs_stock_old',newOrder,newPayment,4000,'paid')).expect(409);expect(required((await pool.query<{stock_disponible:number}>('SELECT stock_disponible FROM vino WHERE id=$1',[wine1])).rows[0]).stock_disponible).toBe(3);expect(required((await pool.query<{total:number}>('SELECT count(*)::int total FROM evento_webhook_stripe WHERE stripe_event_id=$1',['evt_stock'])).rows[0]).total).toBe(0);const oldNegative=await send(signed('evt_old_expired','checkout.session.expired','cs_stock_old',newOrder,newPayment,4000,'unpaid')).expect(200);expect(oldNegative.body).toMatchObject({status:'ignored',pago_estado:'pendiente'});const currentNegative=await send(signed('evt_current_expired','checkout.session.expired','cs_stock_current',newOrder,newPayment,4000,'unpaid')).expect(200);expect(currentNegative.body).toMatchObject({status:'processed',pago_estado:'cancelado',pedido_estado:'pendiente_pago'});});
  it('rechaza firma inválida antes de interpretar el evento',async()=>{const value=event('evt_bad_signature');await send({...value,header:'t=1,v1='+'0'.repeat(64)}).expect(400);});
});
