import { ConflictException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { describe, expect, it, vi } from 'vitest';
import type { SessionActor } from '../src/common/security/session.service.js';
import type { SubpedidosRepository, SubOrderRecord } from '../src/modules/subpedidos/subpedidos.repository.js';
import { deriveOrderState, isSubOrderTransitionAllowed } from '../src/modules/subpedidos/subpedidos.repository.js';
import { SubpedidosService } from '../src/modules/subpedidos/subpedidos.service.js';

const ID='11111111-1111-4111-8111-111111111111',BODEGA='22222222-2222-4222-8222-222222222222';
const ACTOR:SessionActor={usuarioId:'33333333-3333-4333-8333-333333333333',rol:'bodega',bodegaId:BODEGA,issuedAt:new Date('2026-07-14T09:00:00Z'),expiresAt:new Date('2026-07-14T17:00:00Z')};
const RECORD:SubOrderRecord={id:ID,pedido_id:'44444444-4444-4444-8444-444444444444',bodega_id:BODEGA,estado:'pendiente',subtotal:'10.00',gastos_envio:'2.00',impuestos:'0.00',total:'12.00',fecha_ultimo_cambio_estado:'2026-07-14T10:00:00Z',direccion_envio_snapshot:{nombre_destinatario:'Buyer',direccion:'Calle 1',codigo_postal:'28001',ciudad:'Madrid',pais:'ES'},pedido_estado:'pagado',transportista:null,numero_seguimiento:null,fecha_preparacion:null,fecha_envio:null,fecha_entrega_prevista:null,fecha_entrega_real:null,lineas:[]};
function setup(){const repository={bodegaPuedeOperar:vi.fn().mockResolvedValue(true),listar:vi.fn(),obtener:vi.fn(),cambiarEstado:vi.fn()};return{repository,service:new SubpedidosService(repository as unknown as SubpedidosRepository)};}
describe('API-021/022/023 subpedidos',()=>{
  it('fija la matriz normativa completa, incluidos estados terminales e idempotencia',()=>{expect(isSubOrderTransitionAllowed('pendiente','aceptado')).toBe(true);expect(isSubOrderTransitionAllowed('pendiente','enviado')).toBe(false);expect(isSubOrderTransitionAllowed('aceptado','incidencia')).toBe(true);expect(isSubOrderTransitionAllowed('en_preparacion','enviado')).toBe(true);expect(isSubOrderTransitionAllowed('incidencia','en_preparacion')).toBe(true);expect(isSubOrderTransitionAllowed('enviado','entregado')).toBe(true);expect(isSubOrderTransitionAllowed('entregado','enviado')).toBe(false);expect(isSubOrderTransitionAllowed('cancelado','pendiente')).toBe(false);expect(isSubOrderTransitionAllowed('cancelado','cancelado')).toBe(true);});
  it('deriva el estado del pedido para todas las combinaciones normativas',()=>{expect(deriveOrderState(['pendiente','cancelado'])).toBe('pagado');expect(deriveOrderState(['aceptado','pendiente'])).toBe('en_preparacion');expect(deriveOrderState(['enviado','aceptado'])).toBe('parcialmente_enviado');expect(deriveOrderState(['enviado','entregado','cancelado'])).toBe('enviado');expect(deriveOrderState(['entregado','cancelado'])).toBe('entregado');expect(deriveOrderState(['cancelado','cancelado'])).toBe('cancelado');});
  it('pagina y proyecta resumen sin filtrar datos económicos',async()=>{const{repository,service}=setup();repository.listar.mockResolvedValue({items:[RECORD],total:21});await expect(service.listar(ACTOR,{page:2,page_size:20})).resolves.toMatchObject({page:2,page_size:20,total_items:21,total_pages:2,items:[{id:ID,total:'12.00',moneda:'EUR'}]});});
  it('distingue recurso ajeno, inexistente y transición inválida',async()=>{const{repository,service}=setup();repository.obtener.mockResolvedValueOnce({kind:'foreign'}).mockResolvedValueOnce({kind:'missing'});await expect(service.obtener(ACTOR,ID)).rejects.toBeInstanceOf(ForbiddenException);await expect(service.obtener(ACTOR,ID)).rejects.toBeInstanceOf(NotFoundException);repository.cambiarEstado.mockResolvedValue({kind:'conflict'});await expect(service.cambiarEstado(ACTOR,ID,'enviado')).rejects.toBeInstanceOf(ConflictException);});
  it('exige bodega validada y devuelve detalle contractual',async()=>{const{repository,service}=setup();repository.obtener.mockResolvedValue({kind:'ok',suborder:RECORD});await expect(service.obtener(ACTOR,ID)).resolves.toEqual(expect.objectContaining({estado:'pendiente',totales:{subtotal:'10.00',gastos_envio:'2.00',impuestos:'0.00',total:'12.00',moneda:'EUR'},tracking:{},lineas:[]}));repository.bodegaPuedeOperar.mockResolvedValue(false);await expect(service.obtener(ACTOR,ID)).rejects.toBeInstanceOf(ForbiddenException);});
});
