import { randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { AppModule } from '../src/app.module.js';
import { configureApplication } from '../src/bootstrap.js';
import { SessionService } from '../src/common/security/session.service.js';

const HASH='scrypt$16384$8$1$00000000000000000000000000000000$00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000';
function required<T>(value:T|undefined):T{if(value===undefined)throw new Error('Fixture ausente.');return value;}
describe('API-021/022/023 subpedidos E2E',()=>{
  let app:INestApplication,pool:Pool,token:string,bodega:string,own:string,otherOwn:string,foreign:string,pedido:string,pago:string,wine:string;
  beforeAll(async()=>{pool=new Pool({connectionString:process.env.DATABASE_URL});const moduleRef=await Test.createTestingModule({imports:[AppModule]}).compile();app=moduleRef.createNestApplication();configureApplication(app as Parameters<typeof configureApplication>[0]);await app.init();
    const createBodega=async(name:string)=>required((await pool.query<{id:string}>(`INSERT INTO bodega(nombre_comercial,estado,tipo,comision) VALUES($1,'aprobada','estandar',10) RETURNING id`,[name])).rows[0]).id;
    bodega=await createBodega(`Bodega ${randomUUID()}`);const foreignBodega=await createBodega(`Bodega ${randomUUID()}`);
    const user=required((await pool.query<{id:string}>(`INSERT INTO usuario(email,password_hash,rol,estado,bodega_id) VALUES($1,$2,'bodega','activo',$3) RETURNING id`,[`sub-${randomUUID()}@test`,HASH,bodega])).rows[0]).id;
    const buyer=required((await pool.query<{id:string}>(`INSERT INTO usuario(email,password_hash,rol,estado) VALUES($1,$2,'comprador','activo') RETURNING id`,[`buyer-${randomUUID()}@test`,HASH])).rows[0]).id;await pool.query(`INSERT INTO comprador(usuario_id,fecha_nacimiento,declaracion_mayoria_edad,aceptacion_condiciones_alcohol) VALUES($1,'1990-01-01',true,true)`,[buyer]);
    const address=required((await pool.query<{id:string}>(`INSERT INTO direccion(propietario_tipo,propietario_id,nombre_identificativo,destinatario,direccion,codigo_postal,ciudad,pais,es_envio,es_facturacion,activa) VALUES('comprador',$1,'Principal','Buyer','Calle 1','28001','Madrid','ES',true,true,true) RETURNING id`,[buyer])).rows[0]).id;
    const cart=required((await pool.query<{id:string}>(`INSERT INTO carrito(comprador_id,estado) VALUES($1,'convertido') RETURNING id`,[buyer])).rows[0]).id;
    pedido=required((await pool.query<{id:string}>(`INSERT INTO pedido(numero_pedido,comprador_id,carrito_id,subtotal,gastos_envio,impuestos,descuentos,total,direccion_envio_id,direccion_envio_snapshot,direccion_facturacion_id,direccion_facturacion_snapshot,estado) VALUES($1,$2,$3,25,0,0,0,25,$4,$5::jsonb,$4,$5::jsonb,'pagado') RETURNING id`,[`TER-${randomUUID()}`,buyer,cart,address,JSON.stringify({nombre_destinatario:'Buyer',direccion:'Calle 1',codigo_postal:'28001',ciudad:'Madrid',pais:'ES'})])).rows[0]).id;
    pago=required((await pool.query<{id:string}>(`INSERT INTO pago(pedido_id,subtotal,gastos_envio,impuestos,comision_marketplace,total_cobrado,total_repartido,total_reembolsado,moneda,estado) VALUES($1,25,0,0,2.5,25,0,0,'EUR','pagado') RETURNING id`,[pedido])).rows[0]).id;
    const sub=async(owner:string,total:number,orderId=pedido,paymentId=pago)=>required((await pool.query<{id:string}>(`INSERT INTO subpedido(pedido_id,bodega_id,pago_id,subtotal,gastos_envio,impuestos,comision_marketplace,total,estado) VALUES($1,$2,$3,$4,0,0,1,$4,'pendiente') RETURNING id`,[orderId,owner,paymentId,total])).rows[0]).id;
    own=await sub(bodega,10);foreign=await sub(foreignBodega,10);
    const secondCart=required((await pool.query<{id:string}>(`INSERT INTO carrito(comprador_id,estado) VALUES($1,'convertido') RETURNING id`,[buyer])).rows[0]).id;
    const secondOrder=required((await pool.query<{id:string}>(`INSERT INTO pedido(numero_pedido,comprador_id,carrito_id,subtotal,gastos_envio,impuestos,descuentos,total,direccion_envio_id,direccion_envio_snapshot,direccion_facturacion_id,direccion_facturacion_snapshot,estado) VALUES($1,$2,$3,5,0,0,0,5,$4,$5::jsonb,$4,$5::jsonb,'pagado') RETURNING id`,[`TER-${randomUUID()}`,buyer,secondCart,address,JSON.stringify({nombre_destinatario:'Buyer',direccion:'Calle 1',codigo_postal:'28001',ciudad:'Madrid',pais:'ES'})])).rows[0]).id;
    const secondPayment=required((await pool.query<{id:string}>(`INSERT INTO pago(pedido_id,subtotal,gastos_envio,impuestos,comision_marketplace,total_cobrado,total_repartido,total_reembolsado,moneda,estado) VALUES($1,5,0,0,0.5,5,0,0,'EUR','pagado') RETURNING id`,[secondOrder])).rows[0]).id;
    otherOwn=await sub(bodega,5,secondOrder,secondPayment);
    wine=required((await pool.query<{id:string}>(`INSERT INTO vino(bodega_id,nombre_comercial,precio,moneda,stock_disponible,disponible_venta,estado) VALUES($1,'Reserva',10,'EUR',7,true,'publicado') RETURNING id`,[bodega])).rows[0]).id;await pool.query(`INSERT INTO pedido_item(pedido_id,subpedido_id,vino_id,bodega_id,nombre_vino_snapshot,bodega_snapshot,precio_unitario,cantidad,importe_total) VALUES($1,$2,$3,$4,'Reserva','Bodega',10,1,10)`,[pedido,own,wine,bodega]);
    token=(await app.get(SessionService).issue({usuarioId:user,rol:'bodega',bodegaId:bodega})).accessToken;
  });
  afterAll(async()=>{await pool.end();await app.close();});const auth=()=>({Authorization:`Bearer ${token}`});
  it('lista únicamente subpedidos propios con paginación estable',async()=>{const response=await request(app.getHttpServer() as Server).get('/bodegas/yo/subpedidos?page=1&page_size=100').set(auth()).expect(200);const ids=(response.body as {items:{id:string}[]}).items.map(item=>item.id);expect(ids).toEqual(expect.arrayContaining([own,otherOwn]));expect(ids).not.toContain(foreign);expect(response.body).toMatchObject({page:1,page_size:100});});
  it('devuelve detalle congelado y distingue ajeno de inexistente',async()=>{const detail=await request(app.getHttpServer() as Server).get(`/bodegas/yo/subpedidos/${own}`).set(auth()).expect(200);expect(detail.body).toMatchObject({id:own,total:'10.00',lineas:[{vino_id:wine,nombre_vino:'Reserva',cantidad:1}],direccion_envio_snapshot:{ciudad:'Madrid'},tracking:{}});await request(app.getHttpServer() as Server).get(`/bodegas/yo/subpedidos/${foreign}`).set(auth()).expect(403);await request(app.getHttpServer() as Server).get(`/bodegas/yo/subpedidos/${randomUUID()}`).set(auth()).expect(404);});
  it('aplica la matriz, recalcula pedido bajo bloqueo e idempotencia no duplica auditoría',async()=>{await request(app.getHttpServer() as Server).patch(`/bodegas/yo/subpedidos/${own}/estado`).set(auth()).send({estado_destino:'aceptado'}).expect(200);expect(required((await pool.query<{estado:string}>('SELECT estado FROM pedido WHERE id=$1',[pedido])).rows[0]).estado).toBe('en_preparacion');await request(app.getHttpServer() as Server).patch(`/bodegas/yo/subpedidos/${own}/estado`).set(auth()).send({estado_destino:'en_preparacion'}).expect(200);await request(app.getHttpServer() as Server).patch(`/bodegas/yo/subpedidos/${own}/estado`).set(auth()).send({estado_destino:'enviado'}).expect(200);expect(required((await pool.query<{estado:string}>('SELECT estado FROM pedido WHERE id=$1',[pedido])).rows[0]).estado).toBe('parcialmente_enviado');await request(app.getHttpServer() as Server).patch(`/bodegas/yo/subpedidos/${own}/estado`).set(auth()).send({estado_destino:'aceptado'}).expect(409);const before=required((await pool.query<{total:number}>(`SELECT count(*)::int total FROM auditoria WHERE entidad_id=$1 AND accion='cambio_estado'`,[own])).rows[0]).total;await request(app.getHttpServer() as Server).patch(`/bodegas/yo/subpedidos/${own}/estado`).set(auth()).send({estado_destino:'enviado'}).expect(200);const after=required((await pool.query<{total:number}>(`SELECT count(*)::int total FROM auditoria WHERE entidad_id=$1 AND accion='cambio_estado'`,[own])).rows[0]).total;expect(after).toBe(before);});
  it('cancelar es exclusivamente logístico: no altera pago ni stock',async()=>{const beforeStock=required((await pool.query<{stock_disponible:number}>('SELECT stock_disponible FROM vino WHERE id=$1',[wine])).rows[0]).stock_disponible;await request(app.getHttpServer() as Server).patch(`/bodegas/yo/subpedidos/${otherOwn}/estado`).set(auth()).send({estado_destino:'cancelado'}).expect(200);const afterStock=required((await pool.query<{stock_disponible:number}>('SELECT stock_disponible FROM vino WHERE id=$1',[wine])).rows[0]).stock_disponible;const payment=required((await pool.query<{estado:string;total_reembolsado:string}>('SELECT estado,total_reembolsado::text FROM pago WHERE id=$1',[pago])).rows[0]);expect(afterStock).toBe(beforeStock);expect(payment).toEqual({estado:'pagado',total_reembolsado:'0.00'});});
});
