import { BadRequestException, ConflictException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { describe, expect, it, vi } from 'vitest';
import type { SessionActor } from '../src/common/security/session.service.js';
import type { WineWriteRequestDto } from '../src/modules/vinos/dto/wine-request.dto.js';
import type { WineRecord } from '../src/modules/vinos/vinos.repository.js';
import type { VinosRepository } from '../src/modules/vinos/vinos.repository.js';
import { VinosService } from '../src/modules/vinos/vinos.service.js';

const BODEGA='22222222-2222-4222-8222-222222222222';const ID='11111111-1111-4111-8111-111111111111';
const ACTOR:SessionActor={usuarioId:'33333333-3333-4333-8333-333333333333',rol:'bodega',bodegaId:BODEGA,issuedAt:new Date('2026-07-14T10:00:00Z'),expiresAt:new Date('2026-07-14T11:00:00Z')};
const INPUT:WineWriteRequestDto={nombre_comercial:'Reserva',precio:'12.50',moneda:'EUR',stock_disponible:10,disponible_venta:true};
const WINE:WineRecord={id:ID,bodega_id:BODEGA,nombre_comercial:'Reserva',slug:null,sku:null,tipo_vino:null,anada:null,pais:null,region:null,denominacion_origen:null,variedades_uva:null,crianza:null,meses_crianza:null,graduacion_alcoholica:null,volumen_ml:null,descripcion_corta:null,descripcion_completa:null,nota_cata:null,maridaje:null,temperatura_servicio:null,certificaciones:null,premios:null,produccion_limitada:null,precio:'12.50',moneda:'EUR',stock_disponible:10,stock_reservado:0,stock_minimo:0,disponible_venta:true,peso_gramos:null,plazo_preparacion_dias:null,botellas_por_caja:null,estado:'borrador',created_at:'2026-07-14T10:00:00Z',updated_at:'2026-07-14T10:00:00Z',bodega_nombre:'Bodega',bodega_slug:null,bodega_logo_url:null,bodega_region:null,bodega_pais:null,bodega_denominacion_origen:null,imagenes:[]};
function setup(){const repository={bodegaPuedeOperar:vi.fn().mockResolvedValue(true),crear:vi.fn(),listar:vi.fn(),obtener:vi.fn(),reemplazar:vi.fn(),solicitarPublicacion:vi.fn()};return{repository,service:new VinosService(repository as unknown as VinosRepository)};}

describe('APIs 007, 008, 032, 033 y 034 — vinos propios',()=>{
  it('crea siempre en borrador y proyecta detalle sin nulos',async()=>{const{repository,service}=setup();repository.crear.mockResolvedValue(WINE);const result=await service.crear(ACTOR,INPUT);expect(repository.crear).toHaveBeenCalledWith(BODEGA,INPUT);expect(result).toMatchObject({id:ID,estado:'borrador',stock_reservado:0,imagenes:[]});expect(result).not.toHaveProperty('slug');});
  it('pagina y filtra exclusivamente por la bodega de sesión',async()=>{const{repository,service}=setup();repository.listar.mockResolvedValue({items:[WINE],total:21});const result=await service.listar(ACTOR,{estado:'borrador',page:2,page_size:20});expect(repository.listar).toHaveBeenCalledWith(BODEGA,'borrador',2,20);expect(result).toMatchObject({page:2,page_size:20,total_items:21,total_pages:2});});
  it('distingue recurso ajeno (403) e inexistente (404) para consulta y reemplazo',async()=>{const{repository,service}=setup();repository.obtener.mockResolvedValueOnce({kind:'foreign'}).mockResolvedValueOnce({kind:'missing'});await expect(service.obtener(ACTOR,ID)).rejects.toBeInstanceOf(ForbiddenException);await expect(service.obtener(ACTOR,ID)).rejects.toBeInstanceOf(NotFoundException);repository.reemplazar.mockResolvedValue({kind:'foreign'});await expect(service.reemplazar(ACTOR,ID,INPUT)).rejects.toBeInstanceOf(ForbiddenException);});
  it('solicitud de publicación oculta propiedad ajena y traduce precondiciones/estado',async()=>{const{repository,service}=setup();repository.solicitarPublicacion.mockResolvedValueOnce({kind:'missing'}).mockResolvedValueOnce({kind:'invalid'}).mockResolvedValueOnce({kind:'conflict'});await expect(service.solicitarPublicacion(ACTOR,ID)).rejects.toBeInstanceOf(NotFoundException);await expect(service.solicitarPublicacion(ACTOR,ID)).rejects.toBeInstanceOf(BadRequestException);await expect(service.solicitarPublicacion(ACTOR,ID)).rejects.toBeInstanceOf(ConflictException);});
  it('rechaza sesión bodega sin asociación',async()=>{const{service}=setup();await expect(service.crear({...ACTOR,bodegaId:undefined},INPUT)).rejects.toBeInstanceOf(ForbiddenException);});
});
