import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import type { SessionActor } from '../../common/security/session.service.js';
import { DireccionesRepository, type AddressRecord, type Owner } from './direcciones.repository.js';
import type { AddressDto } from './dto/address.dto.js';
import type { AddressCreateRequestDto, AddressPatchRequestDto, AddressUse } from './dto/address-request.dto.js';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
@Injectable()
export class DireccionesService{
 constructor(private readonly repository:DireccionesRepository){}
 async crear(actor:SessionActor,key:string,input:AddressCreateRequestDto):Promise<{address:AddressDto;replayed:boolean}>{if(!UUID.test(key))throw new BadRequestException({code:'VALIDATION_ERROR',message:'Idempotency-Key debe ser un UUID válido.'});const request=this.canonical(input);const result=await this.repository.crear(this.owner(actor),key,input,request);if(result.kind==='conflict')throw new ConflictException({code:'CONFLICT',message:'Idempotency-Key ya fue utilizado.'});return result.kind==='replayed'?{address:result.response,replayed:true}:{address:this.project(result.address),replayed:false};}
 async listar(actor:SessionActor,uso?:AddressUse):Promise<AddressDto[]>{return(await this.repository.listar(this.owner(actor),uso)).map(r=>this.project(r));}
 async actualizar(actor:SessionActor,id:string,input:AddressPatchRequestDto):Promise<AddressDto>{if(!UUID.test(id))this.notFound();if(Object.keys(input).length===0)throw new BadRequestException({code:'VALIDATION_ERROR',message:'Debe indicar al menos un campo.'});const result=await this.repository.actualizar(this.owner(actor),id,input);if(result===null)this.notFound();if(result==='inactive'||result==='principal_conflict')throw new ConflictException({code:'CONFLICT',message:'La dirección no puede actualizarse en su estado actual.'});return this.project(result);}
 async desactivar(actor:SessionActor,id:string):Promise<void>{if(!UUID.test(id)||!await this.repository.desactivar(this.owner(actor),id))this.notFound();}
 private owner(actor:SessionActor):Owner{if(actor.rol==='comprador')return{tipo:'comprador',id:actor.usuarioId,usuarioId:actor.usuarioId};if(actor.rol==='bodega'&&actor.bodegaId!==undefined)return{tipo:'bodega',id:actor.bodegaId,usuarioId:actor.usuarioId};throw new ForbiddenException({code:'FORBIDDEN',message:'La sesión no tiene un propietario de dirección válido.'});}
 private canonical(input:AddressCreateRequestDto):Record<string,unknown>{return{uso:input.uso,nombre_destinatario:input.nombre_destinatario,direccion:input.direccion,codigo_postal:input.codigo_postal,ciudad:input.ciudad,pais:input.pais,nombre_identificativo:input.nombre_identificativo??null,empresa:input.empresa??null,direccion_adicional:input.direccion_adicional??null,provincia:input.provincia??null,persona_contacto:input.persona_contacto??null,telefono:input.telefono??null,email:input.email??null,es_principal:input.es_principal??false};}
 private project(r:AddressRecord):AddressDto{const optional=(key:keyof AddressRecord):Record<string,unknown>=>r[key]===null?{}:{[key]:r[key]};return{id:r.id,uso:r.es_envio&&r.es_facturacion?'ambos':r.es_envio?'envio':'facturacion',nombre_destinatario:r.destinatario,direccion:r.direccion,codigo_postal:r.codigo_postal,ciudad:r.ciudad,pais:r.pais,...optional('nombre_identificativo'),...optional('empresa'),...optional('direccion_adicional'),...optional('provincia'),...optional('persona_contacto'),...optional('telefono'),...optional('email'),es_principal:r.es_principal,activa:r.activa,created_at:new Date(r.created_at).toISOString(),updated_at:new Date(r.updated_at).toISOString()};}
 private notFound():never{throw new NotFoundException({code:'RESOURCE_NOT_FOUND',message:'Dirección no encontrada.'});}
}
