import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Route } from 'next';
import { ApiProblem } from '@/lib/api/problem';
import { isUuid } from '@/lib/cart/contracts';
import { formatOrderDate } from '@/lib/orders/contracts';
import { incidentStateLabel,nextIncidentState,type RelatedResource } from '@/lib/admin/contracts';
import { getAdminIncident } from '@/lib/admin/server';
import { transitionIncidentAction } from '../actions';
interface Props{params:Promise<{id:string}>;searchParams:Promise<{updated?:string;error?:string}>}
function resourceRoute(resource:RelatedResource):Route|undefined{if(resource.tipo==='pedido')return `/admin/pedidos/${resource.id}` as Route;if(resource.tipo==='bodega')return `/admin/bodegas/${resource.id}` as Route;if(resource.tipo==='vino')return `/admin/vinos/${resource.id}` as Route;return undefined}
export default async function AdminIncidentPage({params,searchParams}:Props){const {id}=await params;if(!isUuid(id))notFound();let item;try{item=await getAdminIncident(id)}catch(error){if(error instanceof ApiProblem&&[403,404].includes(error.problem.status))notFound();return <section className="screen-state screen-state-error"><h1>No hemos podido cargar la incidencia</h1></section>}const query=await searchParams,next=nextIncidentState(item.estado),route=resourceRoute(item.recurso_relacionado);return <section className="private-page"><nav className="breadcrumbs"><Link href="/admin">Dashboard</Link><span>/</span><Link href="/admin/incidencias">Incidencias</Link><span>/</span><span>{item.id.slice(0,8)}</span></nav><header className="private-heading order-detail-heading"><div><p className="eyebrow">PT-ADM-009</p><h1>{item.tipo}</h1><p>Abierta el {formatOrderDate(item.fecha)}</p></div><span className={`status-badge incident-${item.estado}`}>{incidentStateLabel(item.estado)}</span></header>{query.updated&&<div className="form-status form-success"><p>Estado actualizado y auditado.</p></div>}{query.error&&<div className="form-status form-error"><p>La transición no está permitida o la incidencia ha cambiado.</p></div>}<div className="incident-layout"><section className="review-copy"><h2>Descripción</h2><p>{item.descripcion}</p><dl><div><dt>Recurso relacionado</dt><dd>{item.recurso_relacionado.tipo}</dd></div><div><dt>Identificador</dt><dd><code>{item.recurso_relacionado.id}</code></dd></div><div><dt>Última actualización</dt><dd>{formatOrderDate(item.updated_at)}</dd></div></dl>{route&&<Link className="button secondary" href={route}>Abrir recurso relacionado</Link>}</section><aside className="checkout-summary"><h2>Siguiente paso</h2>{next===undefined?<p>La incidencia está cerrada y no admite reapertura.</p>:<><p>El ciclo es secuencial y no permite saltos ni retrocesos.</p><form action={transitionIncidentAction}><input name="incidencia_id" type="hidden" value={item.id}/><input name="estado_destino" type="hidden" value={next}/><button className="button primary" type="submit">Marcar como {incidentStateLabel(next).toLowerCase()}</button></form></>}</aside></div></section>}
