import { BadRequestException,ConflictException,ForbiddenException,GoneException,Inject,Injectable,NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { isUUID } from 'class-validator';
import type { SessionActor } from '../../common/security/session.service.js';
import { ConfirmationTokenService,type ConfirmationClaims } from './confirmation-token.service.js';
import type { ImageConfirmRequestDto,ImagePatchRequestDto,UploadRequestDto } from './dto/image-request.dto.js';
import type { ImageDto,UploadAuthorization } from './dto/image.dto.js';
import { ImagenesRepository,type ImageRecord } from './imagenes.repository.js';
import { OBJECT_STORAGE,type ObjectStorageService } from './object-storage.service.js';
const UPLOAD_TTL=600;const CONFIRM_TTL=1800;

@Injectable()
export class ImagenesService{
 private readonly cdn:string;
 constructor(private readonly repository:ImagenesRepository,private readonly tokens:ConfirmationTokenService,@Inject(OBJECT_STORAGE) private readonly storage:ObjectStorageService,config:ConfigService){this.cdn=config.getOrThrow<string>('OBJECT_STORAGE_CDN_BASE_URL').replace(/\/$/,'');}
 async autorizar(actor:SessionActor,vinoId:string,input:UploadRequestDto):Promise<UploadAuthorization>{const bodegaId=await this.operationalBodega(actor);await this.assertOwned(vinoId,bodegaId);const now=Math.floor(Date.now()/1000);const key=`vinos/${bodegaId}/${vinoId}/${input.upload_id}.${this.extension(input.content_type)}`;const claims:ConfirmationClaims={v:1,uploadId:input.upload_id,key,vinoId,bodegaId,usuarioId:actor.usuarioId,nombreArchivo:input.nombre_archivo,contentType:input.content_type,size:input.tamanio_bytes,checksum:input.checksum_sha256,exp:now+CONFIRM_TTL};const uploadUrl=await this.storage.presignPut({key,contentType:input.content_type,contentLength:input.tamanio_bytes,checksumSha256:input.checksum_sha256,expiresInSeconds:UPLOAD_TTL});return{upload_id:input.upload_id,upload_url:uploadUrl,method:'PUT',required_headers:{'Content-Type':input.content_type,'x-amz-checksum-sha256':input.checksum_sha256,'If-None-Match':'*'},confirmation_token:this.tokens.issue(claims),upload_expires_at:new Date((now+UPLOAD_TTL)*1000).toISOString(),confirmation_expires_at:new Date(claims.exp*1000).toISOString()};}
 async confirmar(actor:SessionActor,vinoId:string,input:ImageConfirmRequestDto):Promise<{image:ImageDto;replayed:boolean}>{const bodegaId=await this.operationalBodega(actor);this.uuid(vinoId);const claims=this.tokens.verify(input.confirmation_token);if(claims===null||claims.uploadId!==input.upload_id||claims.vinoId!==vinoId||claims.bodegaId!==bodegaId||claims.usuarioId!==actor.usuarioId)throw new BadRequestException({code:'VALIDATION_ERROR',message:'El token de confirmación no es válido para esta carga.'});if(claims.exp<=Math.floor(Date.now()/1000))throw new GoneException({code:'TOKEN_EXPIRED',message:'El token de confirmación ha caducado.'});await this.assertOwned(vinoId,bodegaId);const head=await this.storage.head(claims.key);if(head===null)this.notFound();if(head.contentType!==claims.contentType||head.contentLength!==claims.size||head.checksumSha256!==claims.checksum)throw new BadRequestException({code:'VALIDATION_ERROR',message:'El objeto cargado no coincide con la autorización.'});const request={upload_id:input.upload_id,alt_text:input.alt_text,orden:input.orden??0,es_principal:input.es_principal??false};const result=await this.repository.confirmar({id:claims.uploadId,vinoId,bodegaId,usuarioId:actor.usuarioId,nombreArchivo:claims.nombreArchivo,url:`${this.cdn}/${claims.key.split('/').map(encodeURIComponent).join('/')}`,formato:this.extension(claims.contentType),size:claims.size,altText:input.alt_text,orden:input.orden??0,principal:input.es_principal??false,request});if(result.kind==='missing')this.notFound();if(result.kind==='conflict')throw new ConflictException({code:'CONFLICT',message:'La carga ya fue confirmada con otros datos.'});return result.kind==='replayed'?{image:result.response,replayed:true}:{image:this.image(result.image),replayed:false};}
 async actualizar(actor:SessionActor,vinoId:string,imageId:string,input:ImagePatchRequestDto):Promise<ImageDto>{const bodegaId=await this.operationalBodega(actor);this.uuid(vinoId);this.uuid(imageId);if(Object.keys(input).length===0)throw new BadRequestException({code:'VALIDATION_ERROR',message:'Debe indicar al menos un campo.'});await this.assertOwned(vinoId,bodegaId);const result=await this.repository.actualizar(vinoId,bodegaId,imageId,input);if(result.kind==='missing')this.notFound();if(result.kind==='conflict')throw new ConflictException({code:'CONFLICT',message:'La imagen no puede actualizarse.'});return this.image(result.image);}
 async desactivar(actor:SessionActor,vinoId:string,imageId:string):Promise<void>{const bodegaId=await this.operationalBodega(actor);this.uuid(vinoId);this.uuid(imageId);await this.assertOwned(vinoId,bodegaId);const result=await this.repository.desactivar(vinoId,bodegaId,imageId);if(result==='missing')this.notFound();if(result==='conflict')throw new ConflictException({code:'CONFLICT',message:'El vino publicado o en revisión debe conservar al menos una imagen activa.'});}
 private async assertOwned(vinoId:string,bodegaId:string):Promise<void>{this.uuid(vinoId);if(await this.repository.ownership(vinoId,bodegaId)!=='owned')this.notFound();}
 private bodega(actor:SessionActor):string{if(actor.rol!=='bodega'||actor.bodegaId===undefined)throw new ForbiddenException({code:'FORBIDDEN',message:'La sesión no está asociada a una bodega.'});return actor.bodegaId;}
 private async operationalBodega(actor:SessionActor):Promise<string>{const id=this.bodega(actor);if(!await this.repository.bodegaPuedeOperar(id))throw new ForbiddenException({code:'FORBIDDEN',message:'La bodega no está validada para operar.'});return id;}
 private uuid(id:string):void{if(!isUUID(id))this.notFound();}
 private notFound():never{throw new NotFoundException({code:'RESOURCE_NOT_FOUND',message:'Vino o imagen no encontrados.'});}
 private extension(type:ConfirmationClaims['contentType']):'jpeg'|'png'|'webp'{return type==='image/jpeg'?'jpeg':type==='image/png'?'png':'webp';}
 private image(row:ImageRecord):ImageDto{return{id:row.id,url:row.url,es_principal:row.es_principal,orden:row.orden,alt_text:row.alt_text,formato:row.formato,activa:row.activa,fecha_subida:new Date(row.fecha_subida).toISOString(),updated_at:new Date(row.updated_at).toISOString(),...(row.nombre_archivo===null?{}:{nombre_archivo:row.nombre_archivo}),...(row.tamanio_bytes===null?{}:{tamanio_bytes:row.tamanio_bytes}),...(row.resolucion===null?{}:{resolucion:row.resolucion})};}
}
