import { Injectable } from '@nestjs/common';
import type { PoolClient } from 'pg';
import { DatabaseService } from '../../common/database/database.service.js';
import type { ImageDto } from './dto/image.dto.js';

export interface ImageRecord{id:string;url:string;es_principal:boolean;orden:number;alt_text:string;formato:'jpeg'|'png'|'webp';activa:boolean;fecha_subida:Date|string;updated_at:Date|string;nombre_archivo:string|null;tamanio_bytes:number|null;resolucion:string|null}
export type Ownership='owned'|'foreign'|'missing';
export interface ConfirmData{id:string;vinoId:string;bodegaId:string;usuarioId:string;nombreArchivo:string;url:string;formato:'jpeg'|'png'|'webp';size:number;altText:string;orden:number;principal:boolean;request:Record<string,unknown>}
export type ConfirmResult={kind:'created';image:ImageRecord}|{kind:'replayed';response:ImageDto}|{kind:'conflict'}|{kind:'missing'};
export type MutationResult={kind:'updated';image:ImageRecord}|{kind:'missing'}|{kind:'conflict'};
const COLUMNS='id,url,es_principal,orden,alt_text,formato,activa,fecha_subida,updated_at,nombre_archivo,tamanio_bytes,resolucion';

@Injectable()
export class ImagenesRepository{
 constructor(private readonly database:DatabaseService){}
 async bodegaPuedeOperar(bodegaId:string):Promise<boolean>{const rows=await this.database.query<{id:string}>("SELECT id FROM bodega WHERE id=$1 AND estado IN ('aprobada','activa')",[bodegaId]);return rows[0]!==undefined;}
 async ownership(vinoId:string,bodegaId:string):Promise<Ownership>{const rows=await this.database.query<{bodega_id:string}>('SELECT bodega_id FROM vino WHERE id=$1',[vinoId]);const row=rows[0];return row===undefined?'missing':row.bodega_id===bodegaId?'owned':'foreign';}
 async confirmar(data:ConfirmData):Promise<ConfirmResult>{return this.database.withTransaction(async client=>{await this.lock(client,data.vinoId);const own=await client.query('SELECT 1 FROM vino WHERE id=$1 AND bodega_id=$2',[data.vinoId,data.bodegaId]);if(own.rows[0]===undefined)return{kind:'missing'};const audits=await client.query<{valor_nuevo:unknown;identical:boolean}>(`SELECT valor_nuevo,(valor_nuevo->'request')=$3::jsonb AS identical FROM auditoria WHERE usuario_id=$1 AND tipo_entidad='imagen' AND entidad_id=$2 AND accion='confirmar_imagen' ORDER BY fecha_hora ASC LIMIT 1`,[data.usuarioId,data.id,JSON.stringify(data.request)]);const audit=audits.rows[0];if(audit!==undefined){const saved=audit.valor_nuevo as {response?:ImageDto};return audit.identical&&saved.response!==undefined?{kind:'replayed',response:saved.response}:{kind:'conflict'};}const occupied=await client.query('SELECT 1 FROM imagen WHERE id=$1',[data.id]);if(occupied.rows[0]!==undefined)return{kind:'conflict'};if(data.principal)await client.query("UPDATE imagen SET es_principal=false,updated_at=now() WHERE tipo_entidad='vino' AND entidad_id=$1 AND es_principal=true",[data.vinoId]);const rows=await client.query<ImageRecord>(`INSERT INTO imagen (id,tipo_entidad,entidad_id,nombre_archivo,url,formato,tamanio_bytes,es_principal,orden,alt_text,activa,subido_por) VALUES ($1,'vino',$2,$3,$4,$5,$6,$7,$8,$9,true,$10) RETURNING ${COLUMNS}`,[data.id,data.vinoId,data.nombreArchivo,data.url,data.formato,data.size,data.principal,data.orden,data.altText,data.usuarioId]);const image=rows.rows[0];if(image===undefined)throw new Error('No se pudo confirmar la imagen.');const response=this.dto(image);await client.query(`INSERT INTO auditoria (usuario_id,tipo_entidad,entidad_id,accion,valor_nuevo,descripcion,sistema,resultado) VALUES ($1,'imagen',$2,'confirmar_imagen',$3::jsonb,'Imagen confirmada.','backend','correcto')`,[data.usuarioId,data.id,JSON.stringify({request:data.request,response})]);return{kind:'created',image};});}
 async actualizar(vinoId:string,bodegaId:string,imageId:string,input:{alt_text?:string;orden?:number;es_principal?:boolean}):Promise<MutationResult>{return this.database.withTransaction(async client=>{await this.lock(client,vinoId);const own=await client.query('SELECT 1 FROM vino WHERE id=$1 AND bodega_id=$2',[vinoId,bodegaId]);if(own.rows[0]===undefined)return{kind:'missing'};const found=await client.query<ImageRecord>(`SELECT ${COLUMNS} FROM imagen WHERE id=$1 AND tipo_entidad='vino' AND entidad_id=$2 FOR UPDATE`,[imageId,vinoId]);const current=found.rows[0];if(current===undefined||!current.activa)return{kind:'missing'};if(input.es_principal===true&&!current.es_principal)await client.query("UPDATE imagen SET es_principal=false,updated_at=now() WHERE tipo_entidad='vino' AND entidad_id=$1 AND es_principal=true",[vinoId]);const entries=Object.entries(input).filter((entry):entry is [string,boolean|number|string]=>entry[1]!==undefined);const set=entries.map(([key],index)=>`${key}=$${String(index+3)}`);const rows=await client.query<ImageRecord>(`UPDATE imagen SET ${set.join(',')},updated_at=now() WHERE id=$1 AND entidad_id=$2 RETURNING ${COLUMNS}`,[imageId,vinoId,...entries.map(([,value])=>value)]);return{kind:'updated',image:rows.rows[0]??current};});}
 async desactivar(vinoId:string,bodegaId:string,imageId:string):Promise<'ok'|'missing'|'conflict'>{return this.database.withTransaction(async client=>{await this.lock(client,vinoId);const wine=await client.query<{estado:string}>('SELECT estado FROM vino WHERE id=$1 AND bodega_id=$2 FOR UPDATE',[vinoId,bodegaId]);const state=wine.rows[0]?.estado;if(state===undefined)return'missing';const found=await client.query<{activa:boolean;es_principal:boolean}>("SELECT activa,es_principal FROM imagen WHERE id=$1 AND tipo_entidad='vino' AND entidad_id=$2 FOR UPDATE",[imageId,vinoId]);const image=found.rows[0];if(image===undefined)return'missing';if(!image.activa)return'ok';if(state==='pendiente_revision'||state==='publicado'){const count=await client.query<{total:string}>("SELECT count(*)::text AS total FROM imagen WHERE tipo_entidad='vino' AND entidad_id=$1 AND activa=true",[vinoId]);if(Number(count.rows[0]?.total??0)<=1)return'conflict';}await client.query('UPDATE imagen SET activa=false,es_principal=false,updated_at=now() WHERE id=$1',[imageId]);if(image.es_principal)await client.query("UPDATE imagen SET es_principal=true,updated_at=now() WHERE id=(SELECT id FROM imagen WHERE tipo_entidad='vino' AND entidad_id=$1 AND activa=true ORDER BY orden ASC,fecha_subida ASC,id ASC LIMIT 1)",[vinoId]);return'ok';});}
 private lock(client:PoolClient,vinoId:string):Promise<unknown>{return client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[vinoId]);}
 private dto(row:ImageRecord):ImageDto{return{id:row.id,url:row.url,es_principal:row.es_principal,orden:row.orden,alt_text:row.alt_text,formato:row.formato,activa:row.activa,fecha_subida:new Date(row.fecha_subida).toISOString(),updated_at:new Date(row.updated_at).toISOString(),...(row.nombre_archivo===null?{}:{nombre_archivo:row.nombre_archivo}),...(row.tamanio_bytes===null?{}:{tamanio_bytes:row.tamanio_bytes}),...(row.resolucion===null?{}:{resolucion:row.resolucion})};}
}
