import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ApiProblem } from '@/lib/api/problem';
import { isUuid } from '@/lib/cart/contracts';
import { getAdminWinery } from '@/lib/admin/server';
import { validateWineryAction } from '../../moderation-actions';
interface Props{params:Promise<{id:string}>;searchParams:Promise<{validated?:string;error?:string}>}
const value=(input:string|number|undefined):string=>input===undefined?'No indicado':String(input);
export default async function AdminWineryPage({params,searchParams}:Props){const {id}=await params;if(!isUuid(id))notFound();let item;try{item=await getAdminWinery(id)}catch(error){if(error instanceof ApiProblem&&[403,404].includes(error.problem.status))notFound();return <section className="screen-state screen-state-error"><h1>No hemos podido cargar la bodega</h1></section>}const query=await searchParams,canValidate=item.estado==='pendiente_revision';return <section className="private-page"><nav className="breadcrumbs"><Link href="/admin">Dashboard</Link><span>/</span><Link href="/admin/bodegas">Bodegas</Link><span>/</span><span>{item.nombre_comercial}</span></nav><header className="private-heading management-heading"><div><p className="eyebrow">PT-ADM-003</p><h1>{item.nombre_comercial}</h1><p>Estado: {item.estado.replaceAll('_',' ')}.</p></div>{canValidate&&<form action={validateWineryAction}><input name="bodega_id" type="hidden" value={item.id}/><button className="button primary" type="submit">Validar bodega</button></form>}</header>{query.validated&&<div className="form-status form-success"><p>Bodega validada correctamente.</p></div>}{query.error&&<div className="form-status form-error"><p>No se ha podido validar; revisa que la solicitud siga pendiente y esté completa.</p></div>}<div className="review-grid"><section><h2>Identidad fiscal y contacto</h2><dl><div><dt>Razón social</dt><dd>{value(item.razon_social)}</dd></div><div><dt>CIF/VAT</dt><dd>{value(item.cif_vat)}</dd></div><div><dt>Email</dt><dd>{value(item.email_principal)}</dd></div><div><dt>Teléfono</dt><dd>{value(item.telefono)}</dd></div><div><dt>Persona de contacto</dt><dd>{value(item.persona_contacto)}</dd></div><div><dt>Dirección</dt><dd>{value(item.direccion_fisica)}</dd></div><div><dt>Localidad</dt><dd>{[item.codigo_postal,item.ciudad,item.provincia,item.pais_contacto].filter(Boolean).join(', ')||'No indicada'}</dd></div></dl></section><section><h2>Perfil comercial</h2><dl><div><dt>Región</dt><dd>{value(item.region)}</dd></div><div><dt>País</dt><dd>{value(item.pais)}</dd></div><div><dt>Denominación</dt><dd>{value(item.denominacion_origen)}</dd></div><div><dt>Fundación</dt><dd>{value(item.anio_fundacion)}</dd></div><div><dt>Web</dt><dd>{value(item.web)}</dd></div></dl>{item.historia&&<><h3>Historia</h3><p>{item.historia}</p></>}{item.filosofia&&<><h3>Filosofía</h3><p>{item.filosofia}</p></>}</section></div></section>}
