export type AuthFieldErrors=Record<string,string[]>;
export interface AuthFormState{fieldErrors:AuthFieldErrors;formError?:string;requestId?:string;success?:string}
export const initialAuthState:AuthFormState={fieldErrors:{}};
export type UserRole='comprador'|'bodega'|'administrador';
export interface AuthSession{access_token:string;token_type:'Bearer';expires_in:number;expires_at:string;usuario:{id:string;email:string;rol:UserRole;idioma:string;estado:string;nombre?:string;apellidos?:string;bodega_id?:string}}
export interface GenericAck{message:string;request_id:string}
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function add(errors:AuthFieldErrors,field:string,message:string):void{(errors[field]??=[]).push(message)}
export function validateEmail(email:string,errors:AuthFieldErrors):void{if(email.length<3||email.length>254||!emailPattern.test(email))add(errors,'email','Introduce un correo electrónico válido.')}
export function validatePassword(password:string,field:string,errors:AuthFieldErrors):void{if(password.length<12||password.length>128)add(errors,field,'La contraseña debe tener entre 12 y 128 caracteres.')}
export function loginPayload(form:FormData):{value?:{email:string;password:string};errors:AuthFieldErrors}{const errors:AuthFieldErrors={};const email=String(form.get('email')??'').trim().toLowerCase();const password=String(form.get('password')??'');validateEmail(email,errors);validatePassword(password,'password',errors);return Object.keys(errors).length===0?{value:{email,password},errors}:{errors}}
export function recoveryPayload(form:FormData):{value?:{email:string};errors:AuthFieldErrors}{const errors:AuthFieldErrors={};const email=String(form.get('email')??'').trim().toLowerCase();validateEmail(email,errors);return Object.keys(errors).length===0?{value:{email},errors}:{errors}}
export function resetPayload(form:FormData):{value?:{token:string;password_nueva:string;confirmacion_password:string};errors:AuthFieldErrors}{const errors:AuthFieldErrors={};const token=String(form.get('token')??'');const password_nueva=String(form.get('password_nueva')??'');const confirmacion_password=String(form.get('confirmacion_password')??'');if(token.length<32||token.length>512)add(errors,'token','El enlace de recuperación no es válido.');validatePassword(password_nueva,'password_nueva',errors);validatePassword(confirmacion_password,'confirmacion_password',errors);if(password_nueva!==confirmacion_password)add(errors,'confirmacion_password','Las contraseñas no coinciden.');return Object.keys(errors).length===0?{value:{token,password_nueva,confirmacion_password},errors}:{errors}}
function validDateOnly(value:string):boolean{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(`${value}T00:00:00Z`);return !Number.isNaN(date.getTime())&&date.toISOString().slice(0,10)===value}
export function registerPayload(form:FormData):{value?:{email:string;password:string;nombre:string;apellidos:string;fecha_nacimiento:string;declaracion_mayoria_edad:true;aceptacion_condiciones_alcohol:true;idioma:'es'};errors:AuthFieldErrors}{const errors:AuthFieldErrors={};const email=String(form.get('email')??'').trim().toLowerCase();const password=String(form.get('password')??'');const nombre=String(form.get('nombre')??'').trim();const apellidos=String(form.get('apellidos')??'').trim();const fecha_nacimiento=String(form.get('fecha_nacimiento')??'');validateEmail(email,errors);validatePassword(password,'password',errors);if(nombre.length<1||nombre.length>100)add(errors,'nombre','Introduce tu nombre.');if(apellidos.length<1||apellidos.length>100)add(errors,'apellidos','Introduce tus apellidos.');if(!validDateOnly(fecha_nacimiento))add(errors,'fecha_nacimiento','Introduce una fecha válida.');if(form.get('declaracion_mayoria_edad')!=='on')add(errors,'declaracion_mayoria_edad','Debes confirmar que eres mayor de edad.');if(form.get('aceptacion_condiciones_alcohol')!=='on')add(errors,'aceptacion_condiciones_alcohol','Debes aceptar las condiciones de venta de alcohol.');return Object.keys(errors).length===0?{value:{email,password,nombre,apellidos,fecha_nacimiento,declaracion_mayoria_edad:true,aceptacion_condiciones_alcohol:true,idioma:'es'},errors}:{errors}}
export function wineryRegisterPayload(form:FormData):{value?:{nombre_comercial:string;razon_social:string;cif_vat:string;email:string;password:string;persona_contacto:string;telefono:string;aceptacion_condiciones:true;pais_contacto?:string;ciudad?:string;codigo_postal?:string};errors:AuthFieldErrors}{const errors:AuthFieldErrors={};const text=(name:string,max:number)=>{const value=String(form.get(name)??'').trim();if(value.length<1||value.length>max)add(errors,name,'Completa este campo correctamente.');return value};const nombre_comercial=text('nombre_comercial',160),razon_social=text('razon_social',200),cif_vat=text('cif_vat',32),email=String(form.get('email')??'').trim().toLowerCase(),password=String(form.get('password')??''),persona_contacto=text('persona_contacto',100),telefono=text('telefono',32);validateEmail(email,errors);validatePassword(password,'password',errors);if(form.get('aceptacion_condiciones')!=='on')add(errors,'aceptacion_condiciones','Debes aceptar los términos y condiciones.');const optional=(name:string,max:number)=>{const value=String(form.get(name)??'').trim();if(value.length>max)add(errors,name,'El valor es demasiado largo.');return value||undefined};const pais_contacto=optional('pais_contacto',100),ciudad=optional('ciudad',100),codigo_postal=optional('codigo_postal',20);return Object.keys(errors).length===0?{value:{nombre_comercial,razon_social,cif_vat,email,password,persona_contacto,telefono,aceptacion_condiciones:true,...(pais_contacto?{pais_contacto}:{}),...(ciudad?{ciudad}:{}),...(codigo_postal?{codigo_postal}:{})},errors}:{errors}}
function record(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value)}
export function parseAuthSession(value:unknown):AuthSession{if(!record(value)||!record(value.usuario)||typeof value.access_token!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(value.access_token)||value.token_type!=='Bearer'||value.expires_in!==28800||typeof value.expires_at!=='string')throw new Error('Respuesta de sesión inválida.');const expires=new Date(value.expires_at);if(Number.isNaN(expires.getTime())||expires.getTime()<=Date.now()||expires.getTime()>Date.now()+28_800_000+60_000)throw new Error('Caducidad de sesión inválida.');const user=value.usuario;const roles:UserRole[]=['comprador','bodega','administrador'];const languages=['es','en','fr','de','it'];const states=['pendiente_verificacion','activo','suspendido','bloqueado','eliminado'];if(typeof user.id!=='string'||typeof user.email!=='string'||typeof user.rol!=='string'||!roles.includes(user.rol as UserRole)||typeof user.idioma!=='string'||!languages.includes(user.idioma)||typeof user.estado!=='string'||!states.includes(user.estado)||(user.bodega_id!==undefined&&typeof user.bodega_id!=='string')||(user.nombre!==undefined&&typeof user.nombre!=='string')||(user.apellidos!==undefined&&typeof user.apellidos!=='string'))throw new Error('Identidad de sesión inválida.');return value as unknown as AuthSession}
export function destinationForRole(role:UserRole):'/cuenta'|'/bodega'|'/admin'{switch(role){case'comprador':return'/cuenta';case'bodega':return'/bodega';case'administrador':return'/admin'}}
