import { BadRequestException,ConflictException,Injectable,NotFoundException } from '@nestjs/common';
import { isUUID } from 'class-validator';
import { AdminVinosRepository,type AdminWineRecord,type TransitionResult } from './admin-vinos.repository.js';
import type { BodegaAdminWineSummary,PageWineAdminSummary,WineAdminDetail,WineAdminSummary } from './dto/vino-admin.dto.js';
import type { ImageSummary } from '../vinos/dto/wine.dto.js';
@Injectable()
export class AdminVinosService{constructor(private readonly repository:AdminVinosRepository){}
 async listar(page:number,pageSize:number):Promise<PageWineAdminSummary>{const result=await this.repository.listar(page,pageSize);return{items:result.items.map(row=>this.summary(row)),page,page_size:pageSize,total_items:result.total,total_pages:Math.ceil(result.total/pageSize)};}
 async obtener(id:string):Promise<WineAdminDetail>{this.uuid(id);const wine=await this.repository.obtener(id);if(wine===null)this.notFound();return this.detail(wine);}
 async publicar(id:string,adminId:string):Promise<WineAdminDetail>{this.uuid(id);return this.result(await this.repository.publicar(id,adminId));}
 async despublicar(id:string,adminId:string):Promise<WineAdminDetail>{this.uuid(id);return this.result(await this.repository.despublicar(id,adminId));}
 private result(result:TransitionResult):WineAdminDetail{if(result.kind==='missing')this.notFound();if(result.kind==='conflict')throw new ConflictException({code:'CONFLICT',message:'El vino no se encuentra en el estado requerido.'});if(result.kind==='invalid')throw new BadRequestException({code:'VALIDATION_ERROR',message:'El vino o su bodega no cumplen los requisitos de publicación.'});return this.detail(result.wine);}
 private bodega(row:AdminWineRecord):BodegaAdminWineSummary{return{id:row.bodega_id,nombre_comercial:row.bodega_nombre,estado:row.bodega_estado,created_at:this.iso(row.bodega_created_at),...this.optional(row,'bodega_razon_social','razon_social'),...this.optional(row,'bodega_cif_vat','cif_vat'),...this.optional(row,'bodega_pais_contacto','pais_contacto')};}
 private image(row:AdminWineRecord['imagenes'][number]):ImageSummary{return{id:row.id,url:row.url,es_principal:row.es_principal,orden:row.orden,alt_text:row.alt_text,...(row.resolucion===null?{}:{resolucion:row.resolucion})};}
 private summary(row:AdminWineRecord):WineAdminSummary{const principal=row.imagenes.find(image=>image.es_principal);return{id:row.id,nombre_comercial:row.nombre_comercial,estado:row.estado,bodega:this.bodega(row),updated_at:this.iso(row.updated_at),precio:row.precio,moneda:row.moneda,...(principal===undefined?{}:{imagen_principal:this.image(principal)})};}
 private detail(row:AdminWineRecord):WineAdminDetail{const principal=row.imagenes.find(image=>image.es_principal);return{id:row.id,nombre_comercial:row.nombre_comercial,precio:row.precio,moneda:row.moneda,disponible_venta:row.disponible_venta,imagenes:row.imagenes.map(image=>this.image(image)),estado:row.estado,stock_disponible:row.stock_disponible,stock_reservado:row.stock_reservado,stock_minimo:row.stock_minimo,created_at:this.iso(row.created_at),updated_at:this.iso(row.updated_at),bodega:this.bodega(row),...this.optional(row,'slug'),...this.optional(row,'sku'),...this.optional(row,'tipo_vino'),...this.optional(row,'anada'),...this.optional(row,'pais'),...this.optional(row,'region'),...this.optional(row,'denominacion_origen'),...this.optional(row,'variedades_uva'),...this.optional(row,'crianza'),...this.optional(row,'meses_crianza'),...this.optional(row,'graduacion_alcoholica'),...this.optional(row,'volumen_ml'),...this.optional(row,'descripcion_corta'),...this.optional(row,'descripcion_completa'),...this.optional(row,'nota_cata'),...this.optional(row,'maridaje'),...this.optional(row,'temperatura_servicio'),...this.optional(row,'certificaciones'),...this.optional(row,'premios'),...this.optional(row,'produccion_limitada'),...this.optional(row,'peso_gramos'),...this.optional(row,'plazo_preparacion_dias'),...this.optional(row,'botellas_por_caja'),...(principal===undefined?{}:{imagen_principal:this.image(principal)})};}
 private optional(row:AdminWineRecord,key:keyof AdminWineRecord,alias?:string):Record<string,unknown>{const value=row[key];return value===null?{}:{[alias??key]:value};}private iso(value:Date|string):string{return new Date(value).toISOString();}private uuid(id:string):void{if(!isUUID(id))this.notFound();}private notFound():never{throw new NotFoundException({code:'RESOURCE_NOT_FOUND',message:'Vino no encontrado.'});}}
