import { Injectable } from '@nestjs/common';
import type { PoolClient } from 'pg';
import { DatabaseService } from '../../common/database/database.service.js';
import type { WineState } from '../vinos/dto/wine-request.dto.js';
import type { ImageRecord } from '../vinos/vinos.repository.js';
export interface AdminWineRecord{id:string;bodega_id:string;nombre_comercial:string;slug:string|null;sku:string|null;tipo_vino:string|null;anada:number|null;pais:string|null;region:string|null;denominacion_origen:string|null;variedades_uva:string[]|null;crianza:string|null;meses_crianza:number|null;graduacion_alcoholica:string|null;volumen_ml:number|null;descripcion_corta:string|null;descripcion_completa:string|null;nota_cata:string|null;maridaje:string|null;temperatura_servicio:string|null;certificaciones:string[]|null;premios:string[]|null;produccion_limitada:boolean|null;precio:string;moneda:'EUR';stock_disponible:number;stock_reservado:number;stock_minimo:number;disponible_venta:boolean;peso_gramos:number|null;plazo_preparacion_dias:number|null;botellas_por_caja:number|null;estado:WineState;created_at:Date|string;updated_at:Date|string;bodega_nombre:string;bodega_estado:string;bodega_created_at:Date|string;bodega_razon_social:string|null;bodega_cif_vat:string|null;bodega_pais_contacto:string|null;imagenes:ImageRecord[]}
export interface AdminWinePage{items:AdminWineRecord[];total:number}
export type TransitionResult={kind:'updated';wine:AdminWineRecord}|{kind:'missing'}|{kind:'conflict'}|{kind:'invalid'};
const COLUMNS=`v.id,v.bodega_id,v.nombre_comercial,v.slug,v.sku,v.tipo_vino,v.anada,v.pais,v.region,v.denominacion_origen,v.variedades_uva,v.crianza,v.meses_crianza,v.graduacion_alcoholica::text,v.volumen_ml,v.descripcion_corta,v.descripcion_completa,v.nota_cata,v.maridaje,v.temperatura_servicio,v.certificaciones,v.premios,v.produccion_limitada,v.precio::text,v.moneda,v.stock_disponible,v.stock_reservado,v.stock_minimo,v.disponible_venta,v.peso_gramos,v.plazo_preparacion_dias,v.botellas_por_caja,v.estado,v.created_at,v.updated_at,b.nombre_comercial AS bodega_nombre,b.estado AS bodega_estado,b.created_at AS bodega_created_at,b.razon_social AS bodega_razon_social,b.cif_vat AS bodega_cif_vat,b.pais_contacto AS bodega_pais_contacto`;
@Injectable()
export class AdminVinosRepository{constructor(private readonly database:DatabaseService){}
 async listar(page:number,pageSize:number):Promise<AdminWinePage>{const count=await this.database.query<{total:string}>("SELECT count(*)::text AS total FROM vino WHERE estado='pendiente_revision'");const rows=await this.database.query<Omit<AdminWineRecord,'imagenes'>>(`SELECT ${COLUMNS} FROM vino v JOIN bodega b ON b.id=v.bodega_id WHERE v.estado='pendiente_revision' ORDER BY v.created_at DESC,v.id DESC LIMIT $1 OFFSET $2`,[pageSize,(page-1)*pageSize]);return{items:await this.images(rows),total:Number(count[0]?.total??0)};}
 async obtener(id:string):Promise<AdminWineRecord|null>{const rows=await this.database.query<Omit<AdminWineRecord,'imagenes'>>(`SELECT ${COLUMNS} FROM vino v JOIN bodega b ON b.id=v.bodega_id WHERE v.id=$1`,[id]);return(await this.images(rows))[0]??null;}
 publicar(id:string,adminId:string):Promise<TransitionResult>{return this.transition(id,adminId,'pendiente_revision','publicado',true);}
 despublicar(id:string,adminId:string):Promise<TransitionResult>{return this.transition(id,adminId,'publicado','oculto',false);}
 private async transition(id:string,adminId:string,from:WineState,to:WineState,checkFitness:boolean):Promise<TransitionResult>{return this.database.withTransaction(async client=>{await this.lock(client,id);const locked=await client.query<{estado:WineState;nombre_comercial:string;precio:string;moneda:string;stock_disponible:number;disponible_venta:boolean;bodega_estado:string;fecha_publicacion:Date|string|null}>(`SELECT v.estado,v.nombre_comercial,v.precio::text,v.moneda,v.stock_disponible,v.disponible_venta,v.fecha_publicacion,b.estado AS bodega_estado FROM vino v JOIN bodega b ON b.id=v.bodega_id WHERE v.id=$1 FOR UPDATE OF v`,[id]);const current=locked.rows[0];if(current===undefined)return{kind:'missing'};if(current.estado!==from)return{kind:'conflict'};if(checkFitness){const image=await client.query("SELECT 1 FROM imagen WHERE tipo_entidad='vino' AND entidad_id=$1 AND activa=true AND length(btrim(alt_text))>0 LIMIT 1",[id]);if(!['aprobada','activa'].includes(current.bodega_estado)||current.nombre_comercial.trim()===''||Number(current.precio)<=0||current.moneda!=='EUR'||current.stock_disponible<=0||!current.disponible_venta||image.rows[0]===undefined)return{kind:'invalid'};}const published=to==='publicado';await client.query(`UPDATE vino SET estado=$2,fecha_publicacion=CASE WHEN $3 THEN now() ELSE fecha_publicacion END,updated_at=now() WHERE id=$1`,[id,to,published]);const action=published?'publicar_vino':'despublicar_vino';const updated=await client.query<{fecha_publicacion:Date|string|null}>('SELECT fecha_publicacion FROM vino WHERE id=$1',[id]);await client.query(`INSERT INTO auditoria (usuario_id,tipo_entidad,entidad_id,accion,valor_anterior,valor_nuevo,descripcion,sistema,resultado) VALUES ($1,'vino',$2,$3,$4::jsonb,$5::jsonb,$6,'backend','correcto')`,[adminId,id,action,JSON.stringify({estado:from,fecha_publicacion:current.fecha_publicacion}),JSON.stringify({estado:to,fecha_publicacion:updated.rows[0]?.fecha_publicacion??null}),published?'Vino publicado.':'Vino despublicado.']);return{kind:'updated',wine:this.required(await this.fetchClient(client,id))};});}
 private async fetchClient(client:PoolClient,id:string):Promise<AdminWineRecord|null>{const rows=await client.query<Omit<AdminWineRecord,'imagenes'>>(`SELECT ${COLUMNS} FROM vino v JOIN bodega b ON b.id=v.bodega_id WHERE v.id=$1`,[id]);return(await this.imagesClient(client,rows.rows))[0]??null;}
 private async images(rows:Omit<AdminWineRecord,'imagenes'>[]):Promise<AdminWineRecord[]>{if(rows.length===0)return[];const imgs=await this.database.query<ImageRecord&{entidad_id:string}>("SELECT id,entidad_id,url,es_principal,orden,alt_text,resolucion FROM imagen WHERE tipo_entidad='vino' AND entidad_id=ANY($1::uuid[]) AND activa=true ORDER BY es_principal DESC,orden,id",[rows.map(row=>row.id)]);return rows.map(row=>({...row,imagenes:imgs.filter(img=>img.entidad_id===row.id)}));}
 private async imagesClient(client:PoolClient,rows:Omit<AdminWineRecord,'imagenes'>[]):Promise<AdminWineRecord[]>{if(rows.length===0)return[];const imgs=await client.query<ImageRecord&{entidad_id:string}>("SELECT id,entidad_id,url,es_principal,orden,alt_text,resolucion FROM imagen WHERE tipo_entidad='vino' AND entidad_id=ANY($1::uuid[]) AND activa=true ORDER BY es_principal DESC,orden,id",[rows.map(row=>row.id)]);return rows.map(row=>({...row,imagenes:imgs.rows.filter(img=>img.entidad_id===row.id)}));}
 private lock(client:PoolClient,id:string):Promise<unknown>{return client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[id]);}private required(value:AdminWineRecord|null):AdminWineRecord{if(value===null)throw new Error('No se pudo recuperar el vino.');return value;}}
