import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { ApiProblem } from '@/lib/api/problem';
import { isUuid } from '@/lib/cart/contracts';
import { WineryWineForm } from '@/components/winery-wine-form';
import { getWineryWine } from '@/lib/winery/server';
import { wineStateLabel } from '@/lib/winery/contracts';
import { requestPublicationAction } from '../../catalog-actions';
interface Props{params:Promise<{id:string}>;searchParams:Promise<{error?:string;created?:string;updated?:string;requested?:string}>}
export default async function WineryWinePage({params,searchParams}:Props){const {id}=await params;if(!isUuid(id))notFound();let wine;try{wine=await getWineryWine(id)}catch(error){if(error instanceof ApiProblem&&[403,404].includes(error.problem.status))notFound();return <section className="screen-state screen-state-error"><h1>No hemos podido cargar el vino</h1></section>}const query=await searchParams;const canRequest=['borrador','oculto'].includes(wine.estado);return <section className="private-page"><nav className="breadcrumbs"><Link href="/bodega/vinos">Vinos</Link><span>/</span><span>{wine.nombre_comercial}</span></nav><header className="private-heading management-heading"><div><p className="eyebrow">PT-BOD-005/006</p><h1>{wine.nombre_comercial}</h1><p>Estado: {wineStateLabel(wine.estado)} · {wine.imagenes.length} imágenes activas.</p></div>{canRequest&&<form action={requestPublicationAction}><input type="hidden" name="vino_id" value={wine.id}/><button className="button secondary" type="submit">Solicitar publicación</button></form>}</header>{(query.created||query.updated)&&<div className="form-status form-success"><p>Vino guardado correctamente.</p></div>}{query.requested&&<div className="form-status form-success"><p>Vino enviado a revisión administrativa.</p></div>}{query.error&&<div className="form-status form-error"><p>{query.error==='publicacion'?'Para solicitar publicación debe estar completo, disponible, con stock y al menos una imagen confirmada.':'No se han podido guardar los cambios.'}</p></div>}<section className="image-management"><h2>Imágenes</h2>{wine.imagenes.length===0?<p>Aún no hay imágenes confirmadas. La carga directa se habilitará en el siguiente corte.</p>:<div className="image-list">{wine.imagenes.map(image=><figure key={image.id}><Image src={image.url} alt={image.alt_text} width={320} height={320}/><figcaption>{image.alt_text}{image.es_principal?' · Principal':''}</figcaption></figure>)}</div>}</section><WineryWineForm wine={wine}/></section>}
