import {createServer} from 'node:http';

const wineId='11111111-1111-4111-8111-111111111111',wineryId='22222222-2222-4222-8222-222222222222',userId='33333333-3333-4333-8333-333333333333',token='A'.repeat(43);
const wine={id:wineId,nombre_comercial:'Reserva E2E',precio:'18.50',moneda:'EUR',disponible_venta:true,bodega:{id:wineryId,nombre_comercial:'Bodega Determinista'},tipo_vino:'Tinto',region:'Rioja',denominacion_origen:'DOCa Rioja'};
const profile={id:wineryId,nombre_comercial:'Bodega Determinista',estado:'activa',created_at:'2026-01-01T00:00:00Z',updated_at:'2026-07-14T00:00:00Z',region:'Rioja',pais:'España',email_principal:'bodega@teralya.test'};
function send(response,status,body){response.writeHead(status,{'Content-Type':'application/json'});response.end(JSON.stringify(body))}
const server=createServer(async(request,response)=>{const url=new URL(request.url??'/',`http://${request.headers.host}`);if(request.method==='GET'&&url.pathname==='/health')return send(response,200,{status:'ok'});if(request.method==='GET'&&url.pathname==='/vinos')return send(response,200,{items:[wine],page:1,page_size:20,total_items:1,total_pages:1});if(request.method==='POST'&&url.pathname==='/auth/login'){let raw='';for await(const chunk of request)raw+=chunk;const input=JSON.parse(raw),email=String(input.email),role=email.startsWith('admin')?'administrador':email.startsWith('bodega')?'bodega':'comprador';return send(response,200,{access_token:token,token_type:'Bearer',expires_in:28800,expires_at:new Date(Date.now()+7*60*60*1000).toISOString(),usuario:{id:userId,email,rol:role,idioma:'es',estado:'activo',...(role==='bodega'?{bodega_id:wineryId}:{})}})}if(request.headers.authorization===`Bearer ${token}`){if(request.method==='GET'&&url.pathname==='/admin/dashboard')return send(response,200,{ventas_dia:{importe:'185.00',moneda:'EUR',num_pedidos:10},pedidos_pendientes:3});if(request.method==='GET'&&url.pathname==='/pedidos')return send(response,200,{items:[],page:1,page_size:20,total_items:0,total_pages:0});if(request.method==='GET'&&url.pathname==='/bodegas/yo/perfil')return send(response,200,profile);if(request.method==='PATCH'&&url.pathname==='/bodegas/yo/perfil')return send(response,200,{...profile,region:'Ribera del Duero',updated_at:new Date().toISOString()})}return send(response,404,{type:'https://teralya.es/problems/resource-not-found',title:'Resource Not Found',status:404,detail:'Recurso no simulado.',code:'RESOURCE_NOT_FOUND',request_id:'44444444-4444-4444-8444-444444444444',retryable:false})});
server.listen(3001,'127.0.0.1');
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(()=>process.exit(0)));
