import { afterEach,describe,expect,it,vi } from 'vitest';
import { ApiProblem } from '../src/lib/api/problem';
vi.mock('server-only',()=>({}));
const apiRequest=vi.fn();const writeSession=vi.fn();const redirect=vi.fn(()=>{throw new Error('NEXT_REDIRECT')});
vi.mock('../src/lib/api/client',()=>({apiRequest}));
vi.mock('../src/lib/session/session',()=>({writeSession}));
vi.mock('next/navigation',()=>({redirect}));
function form(values:Record<string,string>):FormData{const result=new FormData();for(const[key,value]of Object.entries(values))result.set(key,value);return result}
const auth={access_token:'A'.repeat(43),token_type:'Bearer',expires_in:28800,expires_at:'2026-07-14T18:00:00Z',usuario:{id:'user',email:'buyer@example.com',rol:'comprador',idioma:'es',estado:'activo'}};
afterEach(()=>{vi.useRealTimers();vi.clearAllMocks()});
describe('Server Actions de autenticación',()=>{it('guarda sesión HttpOnly y redirige tras login correcto',async()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-07-14T10:00:00Z'));apiRequest.mockResolvedValue(auth);const{loginAction}=await import('../src/app/(access)/actions');await expect(loginAction({fieldErrors:{}},form({email:'buyer@example.com',password:'password-larga'}))).rejects.toThrow('NEXT_REDIRECT');expect(writeSession).toHaveBeenCalledWith('A'.repeat(43),{usuario_id:'user',rol:'comprador'},new Date('2026-07-14T18:00:00Z'));expect(redirect).toHaveBeenCalledWith('/cuenta')});it('no escribe cookie ante credenciales incorrectas y conserva referencia',async()=>{apiRequest.mockRejectedValue(new ApiProblem({type:'about:blank',title:'Unauthorized',status:401,detail:'No autorizado',code:'AUTHENTICATION_REQUIRED',request_id:'request-id',retryable:false}));const{loginAction}=await import('../src/app/(access)/actions');const result=await loginAction({fieldErrors:{}},form({email:'buyer@example.com',password:'password-larga'}));expect(result).toMatchObject({formError:'El correo o la contraseña no son correctos.',requestId:'request-id'});expect(writeSession).not.toHaveBeenCalled()});it('mantiene anti-enumeración en recuperación',async()=>{apiRequest.mockResolvedValue({message:'ok',request_id:'id'});const{recoveryAction}=await import('../src/app/(access)/actions');const result=await recoveryAction({fieldErrors:{}},form({email:'unknown@example.com'}));expect(result.success).toContain('Si existe una cuenta');expect(result.success).not.toContain('unknown@example.com')})});
